import { Dimensions, StyleSheet } from 'react-native';
import { responsiveFontSize, responsiveHeight, responsiveSpacing, responsiveWidth } from '../utils/responsive';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F3F5FC',
	},
	brandHeader: {
		backgroundColor: '#31429B',
	},
	brandRow: {
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 16, 14, 24),
		paddingTop: responsiveSpacing(SCREEN_HEIGHT, 16, 14, 22),
		paddingBottom: responsiveSpacing(SCREEN_HEIGHT, 18, 14, 24),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	brandLogo: {
		width: responsiveWidth(SCREEN_WIDTH, 0.34, 126, 178),
		height: responsiveHeight(SCREEN_HEIGHT, 0.055, 38, 52),
	},
	nulipaPill: {
		backgroundColor: '#FFFFFF',
		borderRadius: 999,
		paddingVertical: responsiveSpacing(SCREEN_HEIGHT, 7, 6, 10),
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 14, 12, 18),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	nulipaIcon: {
		width: responsiveWidth(SCREEN_WIDTH, 0.055, 20, 28),
		height: responsiveWidth(SCREEN_WIDTH, 0.055, 20, 28),
		marginRight: 6,
	},
	nulipaText: {
		color: '#2D3F9E',
		fontWeight: '800',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 14, 12, 16),
		letterSpacing: 0.3,
	},
	brandAccent: {
		height: responsiveHeight(SCREEN_HEIGHT, 0.012, 8, 14),
		backgroundColor: '#F2C919',
	},
	contentWrap: {
		flex: 1,
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 16, 14, 22),
		paddingTop: responsiveSpacing(SCREEN_HEIGHT, 12, 10, 18),
		paddingBottom: responsiveSpacing(SCREEN_HEIGHT, 8, 6, 12),
	},
	userRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 14, 12, 18),
	},
	userInfoRow: {
		flexDirection: 'row',
		alignItems: 'center',
		flex: 1,
		marginRight: 10,
	},
	userTextWrap: {
		flexShrink: 1,
	},
	avatar: {
		width: responsiveWidth(SCREEN_WIDTH, 0.095, 34, 44),
		height: responsiveWidth(SCREEN_WIDTH, 0.095, 34, 44),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.0475, 17, 22),
		marginRight: 10,
	},
	helloText: {
		color: '#637089',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 14, 12, 16),
		lineHeight: 16,
	},
	nameText: {
		color: '#1F2A64',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 20, 18, 24),
		fontWeight: '800',
	},
	actionsRow: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	circleAction: {
		width: responsiveWidth(SCREEN_WIDTH, 0.1, 36, 44),
		height: responsiveWidth(SCREEN_WIDTH, 0.1, 36, 44),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.05, 18, 22),
		borderWidth: 1,
		borderColor: '#CAD4F6',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#FFFFFF',
		marginLeft: 8,
		shadowColor: '#31429B',
		shadowOpacity: 0.08,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 3 },
		elevation: 2,
	},
	composeAction: {
		backgroundColor: '#31429B',
		borderColor: '#31429B',
	},
	adminLoadingWrap: {
		paddingVertical: 10,
		alignItems: 'center',
		justifyContent: 'center',
	},
	segmentedWrap: {
		flexDirection: 'row',
		backgroundColor: '#E6EBFA',
		borderRadius: 18,
		padding: 4,
		borderWidth: 1,
		borderColor: '#D4DCFA',
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 10, 8, 14),
	},
	segmentItem: {
		flex: 1,
		borderRadius: 14,
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: responsiveSpacing(SCREEN_HEIGHT, 7, 6, 9),
	},
	segmentItemMotionWrap: {
		flex: 1,
	},
	segmentItemActive: {
		backgroundColor: '#31429B',
		shadowColor: '#1F2A64',
		shadowOpacity: 0.18,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 3 },
		elevation: 3,
	},
	segmentText: {
		color: '#5B6478',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 14, 12, 16),
		fontWeight: '700',
	},
	segmentTextActive: {
		color: '#FFFFFF',
		fontWeight: '800',
	},
	segmentInnerRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 7,
	},
	segmentCountPill: {
		minWidth: 22,
		height: 22,
		borderRadius: 11,
		paddingHorizontal: 6,
		backgroundColor: '#CFD8F8',
		alignItems: 'center',
		justifyContent: 'center',
	},
	segmentCountPillActive: {
		backgroundColor: '#F2C919',
	},
	segmentCountText: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 11, 10, 13),
		fontWeight: '800',
		color: '#1F2A64',
	},
	segmentCountTextActive: {
		color: '#1F2A64',
	},
	listArea: {
		flex: 1,
	},
	listContent: {
		minHeight: '100%',
		paddingTop: 2,
		paddingBottom: 16,
	},
	loadingWrap: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingTop: 24,
	},
	emptyWrap: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 22,
		paddingTop: 28,
	},
	emptyTitle: {
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 18, 16, 22),
		fontWeight: '800',
		marginBottom: 6,
	},
	emptyText: {
		color: '#6B7280',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 18, 16, 22),
		textAlign: 'center',
	},
	contactCard: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		borderRadius: 18,
		paddingVertical: responsiveSpacing(SCREEN_WIDTH, 10, 8, 12),
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 10, 8, 12),
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 9, 7, 11),
		borderWidth: 1,
		borderColor: '#E5EAFB',
		elevation: 3,
		shadowColor: '#31429B',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 4 },
	},
	groupCard: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		borderRadius: 18,
		paddingVertical: responsiveSpacing(SCREEN_WIDTH, 10, 8, 12),
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 10, 8, 12),
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 9, 7, 11),
		borderWidth: 1,
		borderColor: '#E5EAFB',
		elevation: 3,
		shadowColor: '#31429B',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 4 },
	},
	chatCardPressed: {
		transform: [{ scale: 0.985 }],
		opacity: 0.96,
	},
	contactAvatar: {
		width: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		height: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.0575, 21, 26),
		marginRight: 10,
		borderWidth: 1,
		borderColor: '#D7DFFA',
	},
	contactTextWrap: {
		flex: 1,
	},
	contactTopRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 8,
	},
	contactTimestamp: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 11, 10, 13),
		color: '#7C869B',
		fontWeight: '700',
	},
	groupTextWrap: {
		flex: 1,
	},
	groupTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	groupAvatar: {
		width: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		height: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.0575, 21, 26),
		marginRight: 10,
		borderWidth: 1,
		borderColor: '#D7DFFA',
	},
	groupName: {
		flex: 1,
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 18),
		fontWeight: '800',
	},
	groupUnreadPill: {
		minWidth: responsiveWidth(SCREEN_WIDTH, 0.06, 22, 28),
		height: responsiveWidth(SCREEN_WIDTH, 0.06, 22, 28),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.03, 11, 14),
		paddingHorizontal: 7,
		backgroundColor: '#F2C919',
		alignItems: 'center',
		justifyContent: 'center',
	},
	groupUnreadText: {
		color: '#2A377E',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		fontWeight: '800',
	},
	groupMeta: {
		color: '#6B7280',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		marginTop: 1,
	},
	groupPreview: {
		color: '#374151',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		marginTop: 3,
	},
	contactRightWrap: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	contactUnreadIndicator: {
		minWidth: responsiveWidth(SCREEN_WIDTH, 0.06, 22, 28),
		height: responsiveWidth(SCREEN_WIDTH, 0.06, 22, 28),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.03, 11, 14),
		paddingHorizontal: 7,
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
	},
	contactUnreadText: {
		color: '#FFFFFF',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		fontWeight: '800',
	},
	contactName: {
		color: '#253578',
		fontSize: 15,
		fontWeight: '800',
	},
	contactMeta: {
		color: '#6A7286',
		fontSize: 12,
		marginTop: 2,
	},
	skeletonListWrap: {
		paddingTop: 2,
		paddingBottom: 12,
	},
	skeletonCard: {
		position: 'relative',
		overflow: 'hidden',
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		borderRadius: 18,
		paddingVertical: responsiveSpacing(SCREEN_WIDTH, 10, 8, 12),
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 10, 8, 12),
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 9, 7, 11),
		borderWidth: 1,
		borderColor: '#E5EAFB',
	},
	skeletonAvatar: {
		width: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		height: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.0575, 21, 26),
		marginRight: 10,
		backgroundColor: '#E8EDFF',
	},
	skeletonTextWrap: {
		flex: 1,
	},
	skeletonLinePrimary: {
		height: 12,
		borderRadius: 6,
		backgroundColor: '#DEE6FF',
		width: '62%',
		marginBottom: 8,
	},
	skeletonLineSecondary: {
		height: 10,
		borderRadius: 6,
		backgroundColor: '#E8EDFF',
		width: '84%',
	},
	skeletonTail: {
		width: 18,
		height: 18,
		borderRadius: 9,
		backgroundColor: '#E8EDFF',
		marginLeft: 8,
	},
	skeletonShimmer: {
		position: 'absolute',
		top: 0,
		bottom: 0,
		width: 84,
		backgroundColor: 'rgba(255, 255, 255, 0.48)',
	},
	/* Modal / Action sheet */
	modalOverlay: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: 'rgba(16, 24, 40, 0.42)',
	},
	actionSheetWrap: {
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'flex-end',
		paddingHorizontal: 0,
		paddingBottom: 0,
	},
	actionSheetSafeArea: {
		flex: 1,
		justifyContent: 'flex-end',
		alignItems: 'stretch',
	},
	actionSheet: {
		backgroundColor: '#FFFFFF',
		borderTopLeftRadius: 24,
		borderTopRightRadius: 24,
		paddingVertical: 0,
		maxHeight: SCREEN_HEIGHT * 0.85,
		overflow: 'hidden',
		elevation: 12,
		shadowColor: '#111827',
		shadowOpacity: 0.16,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: -6 },
	},
	actionSheetTitle: {
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 16, 14, 18),
		fontWeight: '800',
		fontFamily: 'Poppins',
		paddingHorizontal: 16,
		paddingVertical: 12,
		borderBottomWidth: 1,
		borderBottomColor: '#E5EAFB',
	},
	actionItem: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingVertical: 15,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: '#EEF2FF',
	},
	actionIcon: {
		marginRight: 12,
	},
	actionText: {
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 16),
		fontWeight: '600',
		fontFamily: 'Poppins',
	},
	favoriteText: {
		color: '#F2C919',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 16),
		fontFamily: 'Poppins',
	},
	destructiveAction: {
		borderTopWidth: 1,
		borderTopColor: '#FEE2E2',
	},
	destructiveText: {
		color: '#DC2626',
		fontWeight: '700',
		fontFamily: 'Poppins',
	},
});

export default styles;