import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  keyboardView: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 50,
  },
  title: {
    fontSize: 28,
    fontFamily: "Poppins_700Bold",
    color: "#1A1A1A",
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
    color: "#64748B",
    marginBottom: 28,
    lineHeight: 22,
  },
  sectionHeader: {
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    color: "#31429B",
    marginTop: 24,
    marginBottom: 14,
    letterSpacing: 0.3,
  },
  fieldLabel: {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    color: "#475569",
    marginBottom: 8,
    marginTop: 6,
  },
  input: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
    color: "#1E293B",
  },
  dropdownButton: {
    minHeight: 54,
    backgroundColor: "#F9FAFB",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 13,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  dropdownButtonDisabled: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    opacity: 0.6,
  },
  dropdownText: {
    flex: 1,
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: "#1E293B",
  },
  dropdownPlaceholder: {
    color: "#94A3B8",
    fontFamily: "Poppins_400Regular",
  },
  dropdownArrow: {
    color: "#31429B",
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    marginTop: -2,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "flex-end",
  },
  modalSafeArea: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#F9FAFB",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
    maxHeight: "78%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 10,
  },
  dobModalCard: {
    maxHeight: "88%",
    minHeight: "78%",
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: "Poppins_700Bold",
    color: "#1A1A1A",
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  dobSelectorsRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
  },
  dobSelectorColumn: {
    flex: 1,
  },
  searchInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontFamily: "Poppins_400Regular",
    marginBottom: 14,
  },
  optionList: {
    paddingBottom: 12,
  },
  optionRow: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#EDF2F7",
  },
  optionText: {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: "#1E293B",
  },
  optionSubtext: {
    marginTop: 4,
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: "#64748B",
  },
  datePickerWrap: {
    width: "100%",
    alignItems: "stretch",
    justifyContent: "flex-start",
    marginBottom: 18,
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 8,
  },
  datePickerActions: {
    flexDirection: "row",
    gap: 12,
  },
  datePickerAction: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  datePickerCancel: {
    backgroundColor: "#F1F5F9",
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
  },
  datePickerConfirm: {
    backgroundColor: "#31429B",
    shadowColor: "#31429B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  datePickerCancelText: {
    color: "#475569",
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
  },
  datePickerConfirmText: {
    color: "#F9FAFB",
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
  },
  modalLoadingState: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  modalLoadingText: {
    fontSize: 13,
    fontFamily: "Poppins_400Regular",
    color: "#64748B",
  },
  emptyStateText: {
    paddingVertical: 20,
    textAlign: "center",
    color: "#64748B",
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
  },
  button: {
    backgroundColor: "#31429B",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 28,
    shadowColor: "#31429B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonDisabled: {
    backgroundColor: "#A0AABF",
    shadowOpacity: 0.1,
  },
  buttonText: {
    color: "#F9FAFB",
    fontSize: 16,
    fontFamily: "Poppins_700Bold",
    letterSpacing: 0.2,
  },
});

export default styles;
