import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F5F7FB',
	},
	content: {
		flexGrow: 1,
		paddingHorizontal: 16,
		paddingBottom: 24,
	},
	headerCard: {
		marginTop: 14,
		marginBottom: 14,
		backgroundColor: '#F9FAFB',
		borderRadius: 22,
		padding: 16,
		elevation: 3,
		shadowColor: '#000',
		shadowOpacity: 0.06,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 4 },
	},
	title: {
		color: '#31429B',
		fontSize: 24,
		lineHeight: 28,
		fontWeight: '900',
	},
	titleRow: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	backButton: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: 'center',
		justifyContent: 'center',
		marginRight: 8,
		backgroundColor: '#EEF2FF',
	},
	subtitle: {
		marginTop: 6,
		color: '#6B7280',
		fontSize: 13,
		lineHeight: 18,
	},
	searchWrap: {
		marginTop: 12,
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#F8FAFC',
		borderWidth: 1,
		borderColor: '#E2E8F0',
		borderRadius: 14,
		paddingHorizontal: 12,
		height: 42,
	},
	searchInput: {
		flex: 1,
		marginLeft: 8,
		color: '#1F2937',
		fontSize: 14,
	},
	loadingWrap: {
		paddingVertical: 24,
		alignItems: 'center',
	},
	emptyCard: {
		backgroundColor: '#F9FAFB',
		borderRadius: 18,
		padding: 18,
		alignItems: 'center',
	},
	emptyTitle: {
		color: '#31429B',
		fontSize: 16,
		fontWeight: '800',
	},
	emptyText: {
		marginTop: 6,
		color: '#6B7280',
		fontSize: 13,
		lineHeight: 18,
		textAlign: 'center',
	},
	contactList: {
		paddingBottom: 8,
	},
	suggestionsSection: {
		marginTop: 4,
	},
	sectionHeaderRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 8,
	},
	sectionHeading: {
		color: '#31429B',
		fontSize: 18,
		fontWeight: '800',
	},
	sectionCaption: {
		color: '#64748B',
		fontSize: 12,
		fontWeight: '600',
	},
	contactCard: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#F9FAFB',
		borderRadius: 18,
		padding: 12,
		marginBottom: 12,
		elevation: 2,
		shadowColor: '#000',
		shadowOpacity: 0.04,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 3 },
	},
	contactAvatar: {
		width: 48,
		height: 48,
		borderRadius: 24,
		marginRight: 12,
		backgroundColor: '#E5E7EB',
	},
	contactTextWrap: {
		flex: 1,
	},
	contactName: {
		color: '#31429B',
		fontSize: 15,
		fontWeight: '800',
	},
	contactMeta: {
		marginTop: 2,
		color: '#6B7280',
		fontSize: 12,
	},
	connectButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
	},
	contactCardInner: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
	},
	requestActions: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	acceptButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
	},
	declineButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: '#F1F5F9',
		alignItems: 'center',
		justifyContent: 'center',
	},
	pendingBadge: {
		backgroundColor: '#EEF2FF',
		borderRadius: 10,
		paddingHorizontal: 10,
		paddingVertical: 4,
	},
	pendingBadgeText: {
		color: '#31429B',
		fontSize: 11,
		fontWeight: '700',
	},
	pendingSection: {
		marginTop: 4,
		marginBottom: 4,
	},
	sectionBadge: {
		backgroundColor: '#31429B',
		borderRadius: 10,
		minWidth: 22,
		height: 22,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 6,
	},
	sectionBadgeText: {
		color: '#F9FAFB',
		fontSize: 11,
		fontWeight: '800',
	},
});

export default styles;

