import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#FFFFFF',
	},
	container: {
		flex: 1,
		backgroundColor: '#F7F9FC',
	},
	chatScreen: {
		flex: 1,
		backgroundColor: '#F7F9FC',
	},
	chatHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 12,
		paddingTop: 8,
		paddingBottom: 10,
		backgroundColor: '#FFFFFF',
		borderBottomWidth: 1,
		borderBottomColor: '#D9E2FF',
		zIndex: 2,
	},
	headerIconButton: {
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F6F9FF',
	},
	headerProfileWrap: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 10,
	},
	headerAvatar: {
		width: 42,
		height: 42,
		borderRadius: 21,
		backgroundColor: '#E5E7EB',
	},
	headerTextWrap: {
		flex: 1,
	},
	headerTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
	},
	headerSubtitle: {
		marginTop: 2,
		fontSize: 12,
		lineHeight: 16,
		color: '#6B7280',
	},
	headerActions: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	chatBody: {
		flex: 1,
		position: 'relative',
		backgroundColor: '#F7F9FC',
	},
	chatBackground: {
		...StyleSheet.absoluteFillObject,
		width: width,
		height: undefined,
		minHeight: 400,
		zIndex: 0,
		opacity: 0.18,
	},
	messagesArea: {
		flex: 1,
		zIndex: 1,
	},
	loadingState: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	messagesScroll: {
		flex: 1,
	},
	messagesContent: {
		paddingHorizontal: 14,
		paddingTop: 18,
		paddingBottom: 16,
	},
	emptyConversationState: {
		flex: 1,
		minHeight: 420,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 24,
	},
	emptyConversationTitle: {
		marginTop: 14,
		fontSize: 20,
		lineHeight: 24,
		fontWeight: '800',
		color: '#24346F',
	},
	emptyConversationText: {
		marginTop: 8,
		fontSize: 14,
		lineHeight: 20,
		textAlign: 'center',
		color: '#6B7280',
	},
	threadErrorText: {
		paddingHorizontal: 14,
		paddingBottom: 8,
		fontSize: 12,
		lineHeight: 16,
		color: '#B42318',
	},
	messageRow: {
		flexDirection: 'row',
		alignItems: 'flex-end',
		marginBottom: 10,
	},
	messageRowOutgoing: {
		justifyContent: 'flex-end',
	},
	messageRowIncoming: {
		justifyContent: 'flex-start',
	},
	messageAvatar: {
		width: 24,
		height: 24,
		borderRadius: 12,
		marginRight: 8,
		backgroundColor: '#E5E7EB',
	},
	messageBubble: {
		maxWidth: '78%',
		borderRadius: 24,
		paddingHorizontal: 14,
		paddingVertical: 10,
		marginBottom: 2,
	},
	messageBubbleOutgoing: {
		backgroundColor: '#31429B',
		borderBottomRightRadius: 24,
	},
	messageBubbleIncoming: {
		backgroundColor: '#FFFFFF',
		borderBottomLeftRadius: 24,
		borderWidth: 1,
		borderColor: '#D9E2FF',
	},
	messageText: {
		fontSize: 16,
		lineHeight: 22,
		fontWeight: '500',
	},
	messageTextOutgoing: {
		color: '#FFFFFF',
	},
	messageTextIncoming: {
		color: '#24346F',
	},
	messageMetaRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginTop: 4,
	},
	messageTime: {
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '600',
		color: '#6B7280',
	},
	reactionsRow: {
		flexDirection: 'row',
		marginTop: 6,
	},
	reactionBubble: {
		backgroundColor: '#F6F9FF',
		borderRadius: 10,
		paddingHorizontal: 6,
		paddingVertical: 2,
		marginRight: 4,
		borderWidth: 1,
		borderColor: '#D9E2FF',
	},
	reactionText: {
		fontSize: 13,
		color: '#31429B',
	},
	bottomInputWrap: {
		flexDirection: 'row',
		alignItems: 'flex-end',
		gap: 10,
		paddingHorizontal: 12,
		paddingTop: 10,
		paddingBottom: 12,
		backgroundColor: '#FFFFFF',
		borderTopWidth: 1,
		borderTopColor: '#D9E2FF',
	},
	bottomInput: {
		flex: 1,
		minHeight: 44,
		maxHeight: 120,
		borderRadius: 22,
		borderWidth: 1,
		borderColor: '#D9E2FF',
		backgroundColor: '#F6F9FF',
		paddingHorizontal: 14,
		paddingVertical: 10,
		fontSize: 15,
		lineHeight: 20,
		color: '#24346F',
	},
	bottomSendButton: {
		width: 44,
		height: 44,
		borderRadius: 22,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#31429B',
	},
	bottomSendButtonDisabled: {
		opacity: 0.5,
	},
	composerWrap: {
		paddingHorizontal: 10,
		paddingTop: 10,
		paddingBottom: 0,
		backgroundColor: 'transparent',
		zIndex: 10,
	},
	composerBar: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		borderRadius: 28,
		paddingHorizontal: 10,
		paddingVertical: 8,
		borderWidth: 1,
		borderColor: '#D9E2FF',
		shadowColor: '#000',
		shadowOpacity: 0.06,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 4 },
		elevation: 3,
	},
	composerIconButton: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: 'center',
		justifyContent: 'center',
	},
	composerInputWrap: {
		flex: 1,
		marginHorizontal: 8,
		backgroundColor: '#F6F9FF',
		borderRadius: 22,
		paddingHorizontal: 14,
		paddingVertical: 8,
	},
	composerInput: {
		color: '#24346F',
		fontSize: 15,
		lineHeight: 20,
		paddingVertical: 0,
		maxHeight: 160,
		minHeight: 36,
	},
	composerEmojiButton: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: 'center',
		justifyContent: 'center',
	},
	composerSendButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#31429B',
	},
	composerSendButtonDisabled: {
		opacity: 0.5,
	},
	attachmentPreview: {
		flexDirection: 'row',
		alignItems: 'center',
		marginTop: 8,
		backgroundColor: '#F6F9FF',
		borderRadius: 12,
		padding: 8,
		borderWidth: 1,
		borderColor: '#D9E2FF',
	},
	attachmentPreviewImage: {
		width: 48,
		height: 48,
		borderRadius: 8,
		marginRight: 10,
	},
	attachmentPreviewFile: {
		flexDirection: 'row',
		alignItems: 'center',
		marginRight: 10,
	},
	attachmentPreviewFileText: {
		marginLeft: 6,
		color: '#31429B',
		fontSize: 15,
	},
	attachmentPreviewRemove: {
		marginLeft: 'auto',
	},
	attachmentModalOverlay: {
		flex: 1,
		backgroundColor: 'rgba(0,0,0,0.25)',
		justifyContent: 'center',
		alignItems: 'center',
	},
	attachmentModalContent: {
		width: 300,
		backgroundColor: '#FFF',
		borderRadius: 16,
		padding: 20,
		alignItems: 'center',
	},
	attachmentModalTitle: {
		fontSize: 18,
		fontWeight: '700',
		color: '#31429B',
		marginBottom: 18,
	},
	attachmentOption: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingVertical: 10,
		width: '100%',
		borderRadius: 8,
		paddingHorizontal: 8,
		marginBottom: 8,
		backgroundColor: '#F6F9FF',
	},
	attachmentOptionText: {
		marginLeft: 10,
		fontSize: 16,
		color: '#31429B',
	},
	attachmentModalClose: {
		marginTop: 10,
		alignSelf: 'stretch',
		alignItems: 'center',
		paddingVertical: 8,
	},
	attachmentModalCloseText: {
		color: '#B42318',
		fontSize: 15,
		fontWeight: '600',
	},
	reactionPickerOverlay: {
		flex: 1,
		backgroundColor: 'rgba(0,0,0,0.18)',
		justifyContent: 'center',
		alignItems: 'center',
	},
	reactionPickerContent: {
		width: 260,
		backgroundColor: '#FFF',
		borderRadius: 16,
		padding: 18,
		alignItems: 'center',
	},
	reactionPickerTitle: {
		fontSize: 16,
		fontWeight: '700',
		color: '#31429B',
		marginBottom: 10,
	},
	reactionPickerRow: {
		flexDirection: 'row',
		justifyContent: 'center',
		marginBottom: 10,
	},
	reactionPickerEmoji: {
		padding: 8,
		borderRadius: 16,
		backgroundColor: '#F6F9FF',
		marginHorizontal: 4,
	},
	reactionPickerEmojiText: {
		fontSize: 22,
	},
	reactionPickerClose: {
		marginTop: 4,
		alignSelf: 'stretch',
		alignItems: 'center',
		paddingVertical: 6,
	},
	reactionPickerCloseText: {
		color: '#B42318',
		fontSize: 15,
		fontWeight: '600',
	},
	typingIndicatorRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginLeft: 18,
		marginBottom: 8,
	},
	typingBubble: {
		backgroundColor: '#F6F9FF',
		borderRadius: 16,
		paddingHorizontal: 14,
		paddingVertical: 7,
		borderWidth: 1,
		borderColor: '#D9E2FF',
	},
	typingText: {
		color: '#31429B',
		fontSize: 14,
		fontStyle: 'italic',
	},
	composerFooterWrap: {
		gap: 8,
	},
	mentionPanel: {
		marginHorizontal: 12,
		marginTop: 4,
		borderRadius: 14,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D9E2FF',
		paddingVertical: 6,
		overflow: 'hidden',
	},
	mentionItem: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	mentionAvatar: {
		width: 28,
		height: 28,
		borderRadius: 14,
		marginRight: 8,
		backgroundColor: '#E5E7EB',
	},
	mentionName: {
		flex: 1,
		color: '#24346F',
		fontSize: 13,
		fontWeight: '700',
	},
});

export default styles;
