import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F5F6FA',
	},
	content: {
		padding: 16,
		paddingBottom: 28,
	},
	card: {
		backgroundColor: '#FFFFFF',
		borderRadius: 22,
		padding: 18,
		borderWidth: 1,
		borderColor: '#E5E7EB',
		shadowColor: '#000',
		shadowOpacity: 0.08,
		shadowRadius: 14,
		shadowOffset: { width: 0, height: 6 },
		elevation: 6,
	},
	cardHeader: {
		flexDirection: 'column',
		alignItems: 'flex-start',
		marginBottom: 18,
	},
	backButton: {
		width: 36,
		height: 36,
		borderRadius: 18,
		alignItems: 'center',
		justifyContent: 'center',
		marginLeft: -4,
		marginBottom: 12,
		backgroundColor: '#F6F9FF',
		borderWidth: 1,
		borderColor: '#D9E2FF',
	},
	editNotice: {
		marginBottom: 12,
		paddingHorizontal: 12,
		paddingVertical: 10,
		borderRadius: 14,
		backgroundColor: '#EEF2FF',
		color: '#31429B',
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '600',
	},
	title: {
		fontSize: 21,
		lineHeight: 25,
		fontWeight: '800',
		color: '#31429B',
		maxWidth: 260,
	},
	subtitle: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 18,
		color: '#6B7280',
		maxWidth: 280,
	},
	audienceOptionsRow: {
		flexDirection: 'row',
		flexWrap: 'nowrap',
		gap: 6,
		marginTop: 12,
		alignSelf: 'stretch',
	},
	audiencePill: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		flex: 1,
		backgroundColor: '#F6F9FF',
		borderWidth: 1,
		borderColor: '#D9E2FF',
		paddingHorizontal: 8,
		paddingVertical: 7,
		borderRadius: 999,
		alignSelf: 'flex-start',
	},
	audiencePillSelected: {
		backgroundColor: '#EAF0FF',
		borderColor: '#AFC0F7',
	},
	audiencePillText: {
		marginLeft: 4,
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '700',
		color: '#31429B',
	},
	audienceCheckIcon: {
		marginLeft: 4,
	},
	composeRow: {
		flexDirection: 'row',
		alignItems: 'stretch',
		marginBottom: 8,
	},
	composeBody: {
		flex: 1,
		minWidth: 0,
		alignSelf: 'stretch',
	},
	avatar: {
        top: -9,
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: '#E5E7EB',
		marginRight: 12,
	},
	composeName: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: '800',
		color: '#404040',
		marginBottom: 8,
	},
	input: {
		minHeight: 150,
		borderWidth: 1,
		borderColor: '#D9E2FF',
		borderRadius: 18,
		backgroundColor: '#F8FAFF',
		paddingHorizontal: 14,
		paddingVertical: 14,
		fontSize: 15,
		lineHeight: 22,
		color: '#1F2937',
	},
	postInput: {
		width: '100%',
		marginTop: -2,
		marginBottom: 14,
	},
	mentionPanel: {
		marginTop: -6,
		marginBottom: 12,
		borderRadius: 14,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#D9E2FF',
		overflow: 'hidden',
	},
	mentionItem: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	mentionAvatar: {
		width: 28,
		height: 28,
		borderRadius: 14,
		marginRight: 8,
		backgroundColor: '#E5E7EB',
	},
	mentionName: {
		flex: 1,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '700',
		color: '#31429B',
	},
	toolbarRow: {
		flexDirection: 'row',
		flexWrap: 'nowrap',
		justifyContent: 'space-between',
		gap: 6,
		marginBottom: 16,
	},
	toolbarButton: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		flex: 1,
		backgroundColor: '#F6F9FF',
		borderWidth: 1,
		borderColor: '#D9E2FF',
		paddingHorizontal: 8,
		paddingVertical: 9,
		borderRadius: 999,
	},
	toolbarButtonText: {
		marginLeft: 4,
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '700',
		color: '#31429B',
	},
	previewCard: {
		borderRadius: 18,
		borderWidth: 1,
		borderColor: '#E5E7EB',
		overflow: 'hidden',
		backgroundColor: '#FFFFFF',
		marginBottom: 18,
	},
	previewImageWrap: {
		minHeight: 160,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F3F4F6',
		padding: 18,
	},
	previewMediaItem: {
		position: 'relative',
		width: '100%',
		overflow: 'visible',
	},
	previewGridItem: {
		position: 'relative',
		width: '48.5%',
		overflow: 'visible',
	},
	previewImage: {
		width: '100%',
		height: 220,
		backgroundColor: '#F3F4F6',
		borderRadius: 0,
	},
	previewVideoTile: {
		width: '100%',
		height: 220,
		borderRadius: 14,
		backgroundColor: '#F8FAFF',
		borderWidth: 1,
		borderColor: '#D9E2FF',
		alignItems: 'center',
		justifyContent: 'center',
	},
	previewVideoText: {
		marginTop: 8,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '700',
		color: '#31429B',
	},
	previewGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		rowGap: 8,
		width: '100%',
	},
	previewThumbnail: {
		width: '100%',
		height: 120,
		borderRadius: 14,
		backgroundColor: '#E5E7EB',
	},
	previewRemoveButton: {
		position: 'absolute',
		top: -8,
		right: -8,
		width: 24,
		height: 24,
		borderRadius: 12,
		backgroundColor: 'rgba(49, 66, 155, 0.88)',
		alignItems: 'center',
		justifyContent: 'center',
		zIndex: 2,
		elevation: 3,
	},
	previewText: {
		marginTop: 10,
		fontSize: 13,
		lineHeight: 18,
		color: '#6B7280',
		textAlign: 'center',
	},
	footerRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	saveDraftButton: {
		paddingHorizontal: 8,
		paddingVertical: 10,
	},
	saveDraftText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: '700',
		color: '#31429B',
	},
	postButton: {
		minWidth: 120,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#31429B',
		paddingHorizontal: 18,
		paddingVertical: 13,
		borderRadius: 16,
	},
	postButtonDisabled: {
		opacity: 0.45,
	},
	postButtonText: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: '800',
		color: '#FFFFFF',
	},
	uploadModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.72)',
		alignItems: 'center',
		justifyContent: 'center',
		padding: 24,
	},
	uploadModalCard: {
		width: '100%',
		maxWidth: 320,
		backgroundColor: '#FFFFFF',
		borderRadius: 22,
		paddingHorizontal: 22,
		paddingVertical: 24,
		alignItems: 'center',
		gap: 10,
		shadowColor: '#000',
		shadowOpacity: 0.16,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 10 },
		elevation: 8,
	},
	uploadModalTitle: {
		fontSize: 17,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
		textAlign: 'center',
	},
	uploadModalText: {
		fontSize: 13,
		lineHeight: 18,
		color: '#6B7280',
		textAlign: 'center',
	},
});

export default styles;