import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F9FAFB',
	},
	scrollContent: {
		paddingBottom: 24,
		backgroundColor: '#F9FAFB',
	},
	searchRow: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 12,
		paddingTop: 14,
		paddingBottom: 10,
	},
	searchFieldWrap: {
		flex: 1,
		height: 40,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: '#D1D5DB',
		backgroundColor: '#F9FAFB',
		flexDirection: 'row',
		alignItems: 'center',
		paddingLeft: 10,
		paddingRight: 12,
		marginRight: 8,
	},
	searchIcon: {
		marginRight: 6,
	},
	searchInput: {
		flex: 1,
		fontSize: 12,
		color: '#3F3F46',
		paddingVertical: 0,
	},
	squareButton: {
		width: 40,
		height: 40,
		borderRadius: 10,
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
		marginLeft: 8,
	},
	accentButton: {
		backgroundColor: '#F2C919',
	},
	sectionTitle: {
		fontSize: 22,
		lineHeight: 26,
		fontWeight: '800',
		color: '#404040',
		paddingHorizontal: 12,
		marginTop: 6,
		marginBottom: 12,
	},
	horizontalCardsRow: {
		paddingLeft: 12,
		paddingRight: 4,
		paddingBottom: 14,
	},
	featuredCardPlaceholder: {
		width: 252,
		height: 134,
		borderRadius: 12,
		backgroundColor: '#F7E08B',
		marginRight: 12,
		padding: 12,
		justifyContent: 'space-between',
		overflow: 'hidden',
	},
	cardBadgeRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	cardBadge: {
		width: 58,
		height: 14,
		borderRadius: 999,
		backgroundColor: 'rgba(49, 66, 155, 0.14)',
	},
	cardBadgeShort: {
		width: 44,
		height: 10,
		borderRadius: 999,
		backgroundColor: 'rgba(49, 66, 155, 0.1)',
	},
	cardIllustration: {
		flex: 1,
		borderRadius: 10,
		backgroundColor: 'rgba(255, 255, 255, 0.32)',
		marginTop: 10,
		marginBottom: 10,
	},
	cardButtonPill: {
		width: 92,
		height: 22,
		borderRadius: 999,
		backgroundColor: '#F2C919',
		alignItems: 'center',
		justifyContent: 'center',
	},
	featuredEventLoadingCard: {
		width: 252,
		height: 220,
		borderRadius: 14,
		backgroundColor: '#F8FAFC',
		borderWidth: 1,
		borderColor: '#E5E7EB',
		marginRight: 12,
		alignItems: 'center',
		justifyContent: 'center',
	},
	featuredEventLoadingText: {
		marginTop: 10,
		fontSize: 12,
		fontWeight: '700',
		color: '#4B5563',
	},
	featuredEventCard: {
		width: 252,
		borderRadius: 14,
		backgroundColor: '#F9FAFB',
		marginRight: 12,
		shadowColor: '#000',
		shadowOpacity: 0.08,
		shadowRadius: 12,
		shadowOffset: { width: 0, height: 6 },
		elevation: 5,
		overflow: 'hidden',
	},
	featuredEventCardPressed: {
		transform: [{ scale: 0.985 }],
		opacity: 0.92,
	},
	featuredEventImage: {
		width: '100%',
		height: 140,
		backgroundColor: '#E5E7EB',
	},
	featuredEventBody: {
		paddingHorizontal: 12,
		paddingTop: 10,
		paddingBottom: 12,
	},
	featuredEventTitle: {
		marginTop: 8,
		fontSize: 15,
		lineHeight: 18,
		fontWeight: '800',
		color: '#31429B',
	},
	featuredEventDescription: {
		marginTop: 4,
		fontSize: 12,
		lineHeight: 16,
		color: '#4B5563',
	},
	featuredEventMetaRow: {
		top: 3,
		marginBottom: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 8,
	},
	featuredEventMetaText: {
		flex: 1,
		fontSize: 11,
		lineHeight: 14,
		color: '#6B7280',
		fontWeight: '700',
	},
	comingSoonTitle: {
		marginTop: 2,
		marginBottom: 14,
	},
	comingSoonRow: {
		paddingLeft: 12,
		paddingRight: 12,
		paddingBottom: 4,
	},
	eventCard: {
		width: 190,
		marginRight: 12,
		borderRadius: 14,
		backgroundColor: '#F9FAFB',
		shadowColor: '#000',
		shadowOpacity: 0.08,
		shadowRadius: 12,
		shadowOffset: { width: 0, height: 6 },
		elevation: 5,
		overflow: 'hidden',
	},
	eventImagePlaceholder: {
		height: 166,
		backgroundColor: '#E5E7EB',
	},
	eventBody: {
		paddingHorizontal: 10,
		paddingTop: 10,
		paddingBottom: 12,
	},
	eventTitleBlock: {
		height: 14,
		borderRadius: 999,
		backgroundColor: '#D1D5DB',
		marginBottom: 8,
		width: '88%',
	},
	eventTitleShortBlock: {
		height: 14,
		borderRadius: 999,
		backgroundColor: '#D1D5DB',
		marginBottom: 12,
		width: '72%',
	},
	eventMetaRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 12,
	},
	eventMetaBlock: {
		height: 12,
		borderRadius: 999,
		backgroundColor: '#E5E7EB',
		width: '46%',
	},
	eventMetaBlockShort: {
		height: 12,
		borderRadius: 999,
		backgroundColor: '#E5E7EB',
		width: '30%',
	},
	registerButton: {
		backgroundColor: '#F2C919',
		borderRadius: 999,
		paddingVertical: 7,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerButtonText: {
		fontSize: 12,
		fontWeight: '800',
		color: '#31429B',
	},
	cardButtonPillText: {
		fontSize: 12,
		fontWeight: '800',
		color: '#31429B',
	},
	featuredEventEmptyCard: {
		width: 252,
		marginRight: 12,
		padding: 16,
		borderRadius: 14,
		backgroundColor: '#F8FAFC',
		borderWidth: 1,
		borderColor: '#E5E7EB',
	},
	featuredEventEmptyTitle: {
		fontSize: 14,
		fontWeight: '800',
		color: '#31429B',
	},
	featuredEventEmptyText: {
		marginTop: 6,
		fontSize: 12,
		lineHeight: 16,
		color: '#4B5563',
	},
	emptyState: {
		marginTop: 18,
		marginHorizontal: 12,
		padding: 14,
		borderRadius: 14,
		backgroundColor: '#F8FAFC',
		borderWidth: 1,
		borderColor: '#E5E7EB',
	},
	emptyStateTitle: {
		fontSize: 16,
		fontWeight: '800',
		color: '#31429B',
		marginBottom: 4,
	},
	emptyStateText: {
		fontSize: 13,
		lineHeight: 18,
		color: '#4B5563',
	},
	calendarOverlay: {
		flex: 1,
		backgroundColor: 'rgba(17, 24, 39, 0.42)',
		justifyContent: 'center',
		alignItems: 'center',
		paddingHorizontal: 20,
	},
	calendarBackdrop: {
		...StyleSheet.absoluteFillObject,
	},
	calendarCard: {
		width: '100%',
		maxWidth: 360,
		borderRadius: 22,
		backgroundColor: '#F9FAFB',
		padding: 18,
		shadowColor: '#000',
		shadowOpacity: 0.18,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 12 },
		elevation: 12,
	},
	calendarPagerWindow: {
		overflow: 'visible',
	},
	calendarPagerContent: {
		alignSelf: 'center',
	},
	calendarHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 14,
	},
	calendarTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
	},
	calendarNavButton: {
		width: 34,
		height: 34,
		borderRadius: 17,
		backgroundColor: '#F7F9FC',
		alignItems: 'center',
		justifyContent: 'center',
	},
	registrationCard: {
		width: '100%',
		maxWidth: 360,
		maxHeight: '72%',
		borderRadius: 22,
		backgroundColor: '#F9FAFB',
		padding: 18,
		shadowColor: '#000',
		shadowOpacity: 0.18,
		shadowRadius: 20,
		shadowOffset: { width: 0, height: 12 },
		elevation: 12,
	},
	registrationHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 14,
	},
	registrationTitle: {
		fontSize: 16,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
	},
	registrationList: {
		paddingBottom: 4,
	},
	registrationEmptyState: {
		alignItems: 'center',
		justifyContent: 'center',
		paddingTop: 28,
		paddingBottom: 10,
	},
	registrationEmptyIconWrap: {
		width: 120,
		height: 120,
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 18,
	},
	registrationEmptyIcon: {
		width: 120,
		height: 120,
	},
	registrationEmptyText: {
		fontSize: 18,
		lineHeight: 24,
		fontWeight: '700',
		textAlign: 'center',
		color: '#4A4A4A',
		maxWidth: 260,
	},
	registrationOkayButton: {
		marginTop: 30,
		minWidth: 180,
		borderRadius: 999,
		backgroundColor: '#F2C919',
		paddingVertical: 12,
		paddingHorizontal: 24,
		alignItems: 'center',
		justifyContent: 'center',
	},
	registrationOkayButtonText: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
	},
	registrationItem: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingVertical: 12,
		paddingHorizontal: 10,
		borderRadius: 16,
		backgroundColor: '#F8FAFC',
		marginBottom: 10,
	},
	registrationItemPressed: {
		opacity: 0.84,
	},
	registrationIconWrap: {
		width: 38,
		height: 38,
		borderRadius: 19,
		backgroundColor: '#F2C919',
		alignItems: 'center',
		justifyContent: 'center',
		marginRight: 12,
	},
	registrationTextWrap: {
		flex: 1,
	},
	registrationItemTitle: {
		fontSize: 14,
		lineHeight: 18,
		fontWeight: '800',
		color: '#1F2937',
	},
	registrationItemMeta: {
		marginTop: 2,
		fontSize: 12,
		lineHeight: 16,
		color: '#6B7280',
	},
	calendarWeekRow: {
		flexDirection: 'row',
		marginBottom: 8,
	},
	calendarWeekLabel: {
		flex: 1,
		textAlign: 'center',
		fontSize: 12,
		fontWeight: '700',
		color: '#6B7280',
	},
	calendarGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
	},
	calendarDayCell: {
		width: '14.2857%',
		aspectRatio: 1,
		alignItems: 'center',
		justifyContent: 'center',
		position: 'relative',
	},
	calendarDayCellEmpty: {
		backgroundColor: 'transparent',
	},
	calendarDayBubble: {
		width: 30,
		height: 30,
		borderRadius: 15,
		alignItems: 'center',
		justifyContent: 'center',
	},
	calendarDayBubbleEvent: {
		backgroundColor: '#EEF2FF',
		borderWidth: 1,
		borderColor: '#C7D2FE',
	},
	calendarDayBubbleToday: {
		backgroundColor: '#F2C919',
	},
	calendarDayBubbleTodayEvent: {
		borderColor: '#F2C919',
	},
	calendarDayBubbleSelected: {
		backgroundColor: '#31429B',
		borderColor: '#31429B',
	},
	calendarDayText: {
		fontSize: 13,
		fontWeight: '700',
		color: '#1F2937',
	},
	calendarDayTextEvent: {
		color: '#31429B',
	},
	calendarDayTextToday: {
		color: '#31429B',
	},
	calendarDayTextTodayEvent: {
		color: '#31429B',
	},
	calendarDayTextSelected: {
		color: '#F9FAFB',
	},
	calendarEventDot: {
		position: 'absolute',
		bottom: 3,
		width: 5,
		height: 5,
		borderRadius: 2.5,
		backgroundColor: '#31429B',
	},
	calendarEventDotToday: {
		backgroundColor: '#31429B',
	},
	calendarDayEventBubble: {
		position: 'absolute',
		bottom: 44,
		width: 168,
		paddingHorizontal: 10,
		paddingTop: 10,
		paddingBottom: 10,
		borderRadius: 12,
		backgroundColor: '#31429B',
		borderWidth: 1,
		borderColor: '#F2C919',
		zIndex: 40,
		elevation: 20,
		shadowColor: '#1F2A64',
		shadowOpacity: 0.16,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
	},
	calendarDayEventBubbleAnchorCenter: {
		left: '50%',
		marginLeft: -84,
	},
	calendarDayEventBubbleAnchorLeft: {
		left: 0,
	},
	calendarDayEventBubbleAnchorRight: {
		right: 0,
	},
	calendarDayEventBubbleItem: {
		marginTop: 5,
		fontSize: 10,
		lineHeight: 12,
		color: '#F8FAFF',
		fontWeight: '700',
		textAlign: 'center',
	},
	calendarDayEventBubbleItemRow: {
		flexDirection: 'column',
		alignItems: 'center',
		marginTop: 3,
		borderRadius: 8,
		paddingVertical: 2,
		paddingHorizontal: 2,
	},
	calendarDayEventBubbleItemRowPressed: {
		opacity: 0.78,
	},
	calendarDayEventBubbleThumb: {
		width: 56,
		height: 56,
		borderRadius: 8,
		backgroundColor: '#EEF2FF',
		borderWidth: 1,
		borderColor: '#F2C919',
	},
	calendarDayEventBubbleMore: {
		marginTop: 6,
		fontSize: 10,
		lineHeight: 12,
		color: '#F2C919',
		fontWeight: '700',
		textAlign: 'center',
	},
	calendarDayEventBubbleArrow: {
		position: 'absolute',
		bottom: -6,
		width: 12,
		height: 12,
		backgroundColor: '#31429B',
		transform: [{ rotate: '45deg' }],
	},
	calendarDayEventBubbleArrowCenter: {
		left: '50%',
		marginLeft: -6,
	},
	calendarDayEventBubbleArrowLeft: {
		left: 18,
	},
	calendarDayEventBubbleArrowRight: {
		right: 18,
	},
});

export default styles;

