import { Dimensions, StyleSheet } from 'react-native';
import { responsiveFontSize, responsiveHeight, responsiveSpacing, responsiveWidth } from '../utils/responsive';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#FFFFFF',
	},
	pageHeaderCard: {
		backgroundColor: '#FFFFFF',
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 22, 16, 28),
		paddingTop: responsiveSpacing(SCREEN_HEIGHT, 18, 14, 24),
		paddingBottom: responsiveSpacing(SCREEN_HEIGHT, 18, 14, 24),
		borderBottomWidth: 1,
		borderBottomColor: '#E7E9F2',
		shadowColor: '#101828',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 3 },
		elevation: 2,
	},
	pageHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: responsiveSpacing(SCREEN_WIDTH, 12, 10, 16),
	},
	pageHeaderTitle: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 20, 18, 26),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 26, 22, 32),
		fontFamily: 'Poppins_700Bold',
		color: '#31429B',
		letterSpacing: -0.3,
	},
	scrollContent: {
		paddingTop: responsiveSpacing(SCREEN_HEIGHT, 12, 10, 18),
		paddingBottom: responsiveSpacing(SCREEN_HEIGHT, 28, 22, 34),
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 12, 10, 16),
	},
	formSurface: {
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#E4E4E4',
		borderRadius: 18,
		padding: responsiveSpacing(SCREEN_WIDTH, 10, 8, 14),
		shadowColor: '#101828',
		shadowOpacity: 0.08,
		shadowRadius: 12,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	eventCard: {
		backgroundColor: '#FFFFFF',
		borderRadius: 16,
		paddingHorizontal: 4,
		paddingTop: 4,
		paddingBottom: 8,
	},
	eventBanner: {
		height: responsiveHeight(SCREEN_HEIGHT, 0.16, 112, 160),
		borderRadius: 14,
		overflow: 'hidden',
		marginBottom: 10,
	},
	eventBannerImage: {
		borderRadius: 14,
	},
	eventBannerOverlay: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: 'rgba(49, 66, 155, 0.08)',
	},
	eventBannerFallback: {
		height: responsiveHeight(SCREEN_HEIGHT, 0.16, 112, 160),
		borderRadius: 14,
		backgroundColor: '#31429B',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 10,
		paddingHorizontal: 18,
	},
	eventBannerIconWrap: {
		width: responsiveWidth(SCREEN_WIDTH, 0.22, 72, 96),
		height: responsiveWidth(SCREEN_WIDTH, 0.22, 72, 96),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.05, 18, 24),
		backgroundColor: 'rgba(255, 255, 255, 0.14)',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 10,
	},
	eventBannerIcon: {
		width: responsiveWidth(SCREEN_WIDTH, 0.16, 52, 72),
		height: responsiveWidth(SCREEN_WIDTH, 0.16, 52, 72),
	},
	eventBannerFallbackText: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 10, 9, 12),
		fontFamily: 'Poppins_600SemiBold',
		color: '#FFFFFF',
		letterSpacing: 0.3,
	},
	eventTitle: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 22, 18, 28),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 28, 24, 34),
		fontFamily: 'Poppins_700Bold',
		color: '#3C3C3C',
		letterSpacing: -0.4,
	},
	eventDescription: {
		marginTop: 10,
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 23, 18, 28),
		fontFamily: 'Poppins_400Regular',
		color: '#5E5E5E',
	},
	metaRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		marginTop: 12,
	},
	metaItem: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: responsiveSpacing(SCREEN_WIDTH, 8, 6, 12),
		flexShrink: 1,
		flexBasis: '48%',
		paddingVertical: 4,
	},
	metaText: {
		flexShrink: 1,
		flex: 1,
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 17, 14, 20),
		fontFamily: 'Poppins_600SemiBold',
		color: '#4F5563',
		minWidth: 0,
	},
	addressRow: {
		marginTop: 8,
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: responsiveSpacing(SCREEN_WIDTH, 6, 4, 10),
	},
	addressText: {
		flex: 1,
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 18, 14, 22),
		fontFamily: 'Poppins_600SemiBold',
		color: '#4F5563',
		minWidth: 0,
	},
	sectionLabel: {
		marginTop: 12,
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 17, 14, 20),
		fontFamily: 'Poppins_600SemiBold',
		color: '#5E5E5E',
	},
	privacyCard: {
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#C7C7C7',
		borderRadius: 12,
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 14, 12, 18),
		paddingVertical: responsiveSpacing(SCREEN_HEIGHT, 14, 12, 18),
	},
	privacyTitle: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 18),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 20, 16, 24),
		fontFamily: 'Poppins_700Bold',
		color: '#404040',
	},
	privacyText: {
		marginTop: 8,
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 22, 18, 26),
		fontFamily: 'Poppins_400Regular',
		color: '#4E4E4E',
	},
	choiceGroup: {
		marginTop: 14,
		gap: responsiveSpacing(SCREEN_HEIGHT, 14, 10, 18),
	},
	choiceRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
	},
	choiceIcon: {
		width: responsiveWidth(SCREEN_WIDTH, 0.045, 16, 20),
		height: responsiveWidth(SCREEN_WIDTH, 0.045, 16, 20),
		justifyContent: 'center',
		alignItems: 'center',
	},
	choiceText: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 18, 14, 22),
		fontFamily: 'Poppins_400Regular',
		color: '#4B4B4B',
	},
	inputCard: {
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#C7C7C7',
		borderRadius: 12,
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 14, 12, 18),
		paddingVertical: responsiveSpacing(SCREEN_HEIGHT, 12, 10, 16),
	},
	inputLabel: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 18),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 20, 16, 24),
		fontFamily: 'Poppins_700Bold',
		color: '#404040',
	},
	inputDescription: {
		marginTop: 8,
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 20, 16, 24),
		fontFamily: 'Poppins_400Regular',
		color: '#5A5A5A',
	},
	inputField: {
		marginTop: 12,
		paddingHorizontal: 0,
		paddingTop: 0,
		paddingBottom: 8,
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		fontFamily: 'Poppins_400Regular',
		color: '#404040',
		borderBottomWidth: 1,
		borderBottomColor: '#CFCFCF',
	},
	confirmationCard: {
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#C7C7C7',
		borderRadius: 12,
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 14, 12, 18),
		paddingVertical: responsiveSpacing(SCREEN_HEIGHT, 12, 10, 16),
	},
	confirmationText: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 21, 17, 25),
		fontFamily: 'Poppins_400Regular',
		color: '#4E4E4E',
	},
	buttonWrap: {
		marginTop: 16,
		paddingTop: 10,
	},
	primaryButton: {
		backgroundColor: '#F7CE18',
		borderRadius: 999,
		minHeight: responsiveHeight(SCREEN_HEIGHT, 0.055, 42, 52),
		alignItems: 'center',
		justifyContent: 'center',
	},
	primaryButtonDisabled: {
		opacity: 0.45,
	},
	primaryButtonText: {
		fontSize: responsiveFontSize(SCREEN_WIDTH, 17, 15, 20),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 22, 18, 26),
		fontFamily: 'Poppins_700Bold',
		color: '#31429B',
		letterSpacing: 0.2,
	},
});

export default styles;
