import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF", 
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: "#FFD404",
    paddingTop: Platform.OS === 'ios' ? 120 : 100, // Adjusted padding so HomeHeader sits comfortably above
  },
  
  // --- NEW YELLOW BANNER ---
  yellowBanner: {
    backgroundColor: "#FFD404",
    paddingHorizontal: 24,
    paddingVertical: 18,
    gap: 16,
  },
  bannerActionRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  bannerActionText: {
    color: "#31429B",
    fontSize: 20,
    fontFamily: "Poppins_700Bold",
    fontWeight: "bold",
    marginLeft: 12,
  },

  // --- WHITE HERO SECTION ---
  whiteHeroSection: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingVertical: 32,
    alignItems: "center",
  },
  heroHeading: {
    color: "#31429B",
    fontSize: 26,
    fontFamily: "Poppins_700Bold",
    fontWeight: "900",
    textAlign: "center",
    lineHeight: 34,
  },
  heroIllustration: {
    width: "100%",
    height: 220,
    marginVertical: 24,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    borderRadius: 999,
    paddingHorizontal: 16,
    height: 48,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#1C1C1E",
    fontFamily: "Poppins_400Regular",
  },

  // --- DARK BLUE EVENTS SECTION ---
  blueEventsSection: {
    backgroundColor: "#384A9C",
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 40,
  },
  sectionTitleYellow: {
    color: "#FFD404",
    fontSize: 24,
    fontFamily: "Poppins_700Bold",
    fontWeight: "bold",
    marginBottom: 20,
  },
  cardsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  eventCard: {
    width: "48%", // Fits two columns perfectly
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginBottom: 20,
    overflow: "hidden",
  },
  eventCardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  cardImage: {
    width: "100%",
    height: 130,
    backgroundColor: "#1F2B67",
  },
  cardContent: {
    padding: 12,
  },
  cardTitle: {
    color: "#1C1C1E",
    fontSize: 14,
    fontFamily: "Poppins_700Bold",
    fontWeight: "bold",
    lineHeight: 20,
    marginBottom: 10,
  },
  cardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  cardMetaText: {
    fontSize: 11,
    color: "#475569",
    fontFamily: "Poppins_500Medium",
    marginLeft: 6,
    flexShrink: 1,
  },
  preRegisterBtn: {
    backgroundColor: "#FFD404",
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  preRegisterBtnText: {
    color: "#31429B",
    fontSize: 12,
    fontFamily: "Poppins_700Bold",
    fontWeight: "bold",
  },
  viewAllOutlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    width: "60%",
    paddingVertical: 12,
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
    borderRadius: 999,
    marginTop: 10,
    marginBottom: 40,
  },
  viewAllOutlineText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    fontWeight: "600",
    marginRight: 8,
  },
  loadingWrap: {
    alignItems: "center",
    paddingVertical: 30,
  },
  loadingText: {
    color: "#FFD404",
    marginTop: 10,
    fontFamily: "Poppins_500Medium",
  },
  emptyStateContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 20,
    borderRadius: 16,
    alignItems: "center",
    marginBottom: 20,
  },
  emptyStateTitle: {
    color: "#FFD404",
    fontSize: 16,
    fontFamily: "Poppins_700Bold",
    marginBottom: 4,
  },
  emptyStateText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: "Poppins_400Regular",
    textAlign: "center",
  },

  // --- MODALS ---
  calendarOverlay: {
    flex: 1,
    backgroundColor: "rgba(17, 24, 39, 0.42)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  calendarBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  calendarCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 22,
    backgroundColor: "#F9FAFB",
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  calendarPagerWindow: {
    overflow: "visible",
  },
  calendarPagerContent: {
    alignSelf: "center",
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  calendarTitle: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    color: "#31429B",
  },
  calendarNavButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#F7F9FC",
    alignItems: "center",
    justifyContent: "center",
  },
  registrationCard: {
    width: "100%",
    maxWidth: 360,
    maxHeight: "72%",
    borderRadius: 22,
    backgroundColor: "#F9FAFB",
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  registrationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  registrationTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "800",
    color: "#31429B",
  },
  registrationList: {
    paddingBottom: 4,
  },
  registrationEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 28,
    paddingBottom: 10,
  },
  registrationEmptyIconWrap: {
    width: 120,
    height: 120,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
  },
  registrationEmptyIcon: {
    width: 120,
    height: 120,
  },
  registrationEmptyText: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
    textAlign: "center",
    color: "#4A4A4A",
    maxWidth: 260,
  },
  registrationOkayButton: {
    marginTop: 30,
    minWidth: 180,
    borderRadius: 999,
    backgroundColor: "#F2C919",
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  registrationOkayButtonText: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "800",
    color: "#31429B",
  },
  registrationItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
    marginBottom: 10,
  },
  registrationItemPressed: {
    opacity: 0.84,
  },
  registrationIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#F2C919",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  registrationTextWrap: {
    flex: 1,
  },
  registrationItemTitle: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    color: "#1F2937",
  },
  registrationItemMeta: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
    color: "#6B7280",
  },
  calendarWeekRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  calendarWeekLabel: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calendarDayCell: {
    width: "14.2857%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  calendarDayCellEmpty: {
    backgroundColor: "transparent",
  },
  calendarDayBubble: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarDayBubbleEvent: {
    backgroundColor: "#EEF2FF",
    borderWidth: 1,
    borderColor: "#C7D2FE",
  },
  calendarDayBubbleToday: {
    backgroundColor: "#F2C919",
  },
  calendarDayBubbleTodayEvent: {
    borderColor: "#F2C919",
  },
  calendarDayBubbleSelected: {
    backgroundColor: "#31429B",
    borderColor: "#31429B",
  },
  calendarDayText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1F2937",
  },
  calendarDayTextEvent: {
    color: "#31429B",
  },
  calendarDayTextToday: {
    color: "#31429B",
  },
  calendarDayTextTodayEvent: {
    color: "#31429B",
  },
  calendarDayTextSelected: {
    color: "#F9FAFB",
  },
  calendarEventDot: {
    position: "absolute",
    bottom: 3,
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: "#31429B",
  },
  calendarEventDotToday: {
    backgroundColor: "#31429B",
  },
  calendarDayEventBubble: {
    position: "absolute",
    bottom: 44,
    width: 168,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 12,
    backgroundColor: "#31429B",
    borderWidth: 1,
    borderColor: "#F2C919",
    zIndex: 40,
    elevation: 20,
    shadowColor: "#1F2A64",
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  calendarDayEventBubbleAnchorCenter: {
    left: "50%",
    marginLeft: -84,
  },
  calendarDayEventBubbleAnchorLeft: {
    left: 0,
  },
  calendarDayEventBubbleAnchorRight: {
    right: 0,
  },
  calendarDayEventBubbleItem: {
    marginTop: 5,
    fontSize: 10,
    lineHeight: 12,
    color: "#F8FAFF",
    fontWeight: "700",
    textAlign: "center",
  },
  calendarDayEventBubbleItemRow: {
    flexDirection: "column",
    alignItems: "center",
    marginTop: 3,
    borderRadius: 8,
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  calendarDayEventBubbleItemRowPressed: {
    opacity: 0.78,
  },
  calendarDayEventBubbleThumb: {
    width: 56,
    height: 56,
    borderRadius: 8,
    backgroundColor: "#EEF2FF",
    borderWidth: 1,
    borderColor: "#F2C919",
  },
  calendarDayEventBubbleMore: {
    marginTop: 6,
    fontSize: 10,
    lineHeight: 12,
    color: "#F2C919",
    fontWeight: "700",
    textAlign: "center",
  },
  calendarDayEventBubbleArrow: {
    position: "absolute",
    bottom: -6,
    width: 12,
    height: 12,
    backgroundColor: "#31429B",
    transform: [{ rotate: "45deg" }],
  },
  calendarDayEventBubbleArrowCenter: {
    left: "50%",
    marginLeft: -6,
  },
  calendarDayEventBubbleArrowLeft: {
    left: 18,
  },
  calendarDayEventBubbleArrowRight: {
    right: 18,
  },
});

export default styles;