import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeAreaTop: { flex: 1, backgroundColor: '#31429B' },
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  mainScrollContent: {
    paddingBottom: 0,
    backgroundColor: '#FFFFFF',
  },
  brandHeader: {
    backgroundColor: '#31429B',
  },
  brandRow: {
    backgroundColor: '#31429B',
    paddingHorizontal: 0,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandAccent: {
    height: 10,
    backgroundColor: '#F2C919',
    width: '100%',
  },
  brandLogo: {
    width: 136,
    height: 42,
  },
  nulipaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    minWidth: 122,
    justifyContent: 'center',
  },
  nulipaIcon: {
    width: 22,
    height: 22,
    marginRight: 6,
  },
  nulipaText: { color: '#31429B', fontWeight: '800', fontSize: 14, letterSpacing: 0.3 },
  profileSection: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 8, paddingTop: 12, paddingBottom: 5, alignItems: 'center' },
  profileInfo: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 48, height: 48, borderRadius: 24, marginRight: 12, borderWidth: 2, borderColor: '#F2C919' },
  greeting: { fontSize: 17, fontWeight: '800', color: '#0A1142' },
  studentId: { fontSize: 10, color: '#666', marginTop: 1 },
  bellIcon: { backgroundColor: '#F2C919', padding: 7, borderRadius: 18 },
  bellIconInner: {
    position: 'relative',
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: -7,
    right: -8,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#D92D20',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
    lineHeight: 10,
  },
  idSection: { paddingHorizontal: 0, paddingVertical: 0, marginTop: 10, marginBottom: 10 },
  profileCardWrapper: {
    marginTop: -8,
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    paddingHorizontal: 14,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    marginBottom: 18,
  },
  tabRow: { flexDirection: 'row', marginBottom: -10, zIndex: 1, marginLeft: 15 },
  activeTab: { backgroundColor: '#F2C919', paddingVertical: 8, paddingHorizontal: 20, borderTopLeftRadius: 10, borderTopRightRadius: 10 },
  activeTabText: { color: '#31429B', fontWeight: 'bold' },
  inactiveTab: { backgroundColor: '#E0E0E0', paddingVertical: 8, paddingHorizontal: 20, borderTopLeftRadius: 10, borderTopRightRadius: 10, marginLeft: 10 },
  inactiveTabText: { color: '#666' },
  idCard: {
    borderRadius: 10,       // Match your face radius
    overflow: 'hidden',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    backgroundColor: '#0A1142',
    width: '92%',           // Take up most of the screen width
    aspectRatio: 1.58,      // This is the "Magic Ratio" for IDs
    alignSelf: 'center',
  },
  idCardPerspective: {
    position: 'relative',
    width: 332,
    height: 217,
    alignSelf: 'center',
    borderRadius: 10,
    overflow: 'visible',
    perspective: 1000,
    
  },
  idCardFace: {
    ...StyleSheet.absoluteFillObject,
    backfaceVisibility: 'hidden',
    borderRadius: 10,
    overflow: 'hidden',
  },
  idCardFrontFace: {
    zIndex: 2,
  },
  idCardBackFace: {
    zIndex: 1,
  },
  idBackground: {
    width: '100%',
    height: '100%',
    flex: 1,
    justifyContent: 'flex-end',
    borderRadius: 10,
    overflow: 'hidden',
  },
  idBackgroundImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  idPhoto: {
    position: 'absolute',
    top: 28,
    right: 6,
    width: 106,
    height: 126,
    zIndex: 10,
  },
  idCardContent: {
    position: 'absolute',
    top: 46,
    left: 20,
    bottom: 22,
    width: 206,
    justifyContent: 'flex-start', //
  },
  idName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
    marginTop: 44,
  },
  idCourse: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 6,
  },
  idClass: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 2,
  },
  idBackImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  sectionContainer: { marginBottom: 0 },
  sectionInset: { marginLeft: 0, marginRight: 0 },
  sectionNudgeRight: { transform: [{ translateX: 0 }] },
  quickLinksSection: { marginTop: 8, marginBottom: 12, paddingBottom: 8 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#31429B', marginBottom: 8, left: 10 },
  horizontalScroll: { flexDirection: 'row' },
  horizontalScrollContent: {
    paddingBottom: 8,
  },
  featuredEventCard: {
    left: 10,
    width: 252,
    height: 280,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginRight: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
    overflow: 'hidden',
  },
  featuredEventCardPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.92,
  },
  featuredEventImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E5E7EB',
  },
  featuredEventBody: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
  },
  cardBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardBadge: {
    width: 58,
    height: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(49, 66, 155, 0.14)',
  },
  cardBadgeShort: {
    width: 44,
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(49, 66, 155, 0.1)',
  },
  cardButtonPill: {
    width: 92,
    height: 22,
    borderRadius: 999,
    backgroundColor: '#F2C919',
    alignItems: 'center',
    justifyContent: 'center',
  },
  featuredEventTitle: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '800',
    color: '#31429B',
  },
  featuredEventDescription: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: '#4B5563',
  },
  featuredEventMetaRow: {
    top: 3,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  featuredEventMetaText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 14,
    color: '#6B7280',
    fontWeight: '700',
  },
  cardButtonPillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#31429B',
  },
  promoLoadingCard: {
    left: 10,
    width: 252,
    height: 220,
    borderRadius: 14,
    marginRight: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoLoadingText: {
    marginTop: 8,
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '700',
  },
  promoEmptyCard: {
    left: 10,
    width: 252,
    height: 220,
    borderRadius: 14,
    marginRight: 12,
    padding: 12,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#D9E1FF',
    justifyContent: 'center',
  },
  quickLinksRow: { flexDirection: 'row', justifyContent: 'space-between' },
  quickLinksScrollContent: {
    paddingBottom: 8,
  },
  quickLinkBox: {
    width: 192,
    minHeight: 64,
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    left: 10,
  },
  quickLinkText: {
    marginLeft: 12,
    color: '#31429B',
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 18,
  },
  quickLinkIcon: {
    width: 36,
    height: 36,
  },
  quickLinkIconNU: {
    width: 26,
    height: 26,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFF',
    height: '85%',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    overflow: 'hidden',
    marginTop: 50,
  },
  modalSideContainer: {
    backgroundColor: '#FFF',
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '100%',
    borderTopLeftRadius: 28,
    borderBottomLeftRadius: 28,
    overflow: 'hidden',
  },
  modalHeader: {
    backgroundColor: '#31429B',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  modalTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  modalHeaderSpacer: {
    width: 28,
  },
  closeBtn: { padding: 5 },
  modalAccentLine: {
    height: 5,
    backgroundColor: '#F2C919',
  },
  notifList: {
    padding: 20,
    flexGrow: 1,
  },
  emptyNotifWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  emptyNotifText: {
    color: '#666',
    fontSize: 14,
  },
  notifCard: {
    flexDirection: 'row',
    marginBottom: 25,
    alignItems: 'flex-start',
    paddingRight: 2,
  },
  notifAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#F2C919',
    marginRight: 15,
  },
  notifBody: {
    flex: 1,
  },
  notifTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  notifName: {
    color: '#31429B',
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 20,
  },
  notifTypePill: {
    backgroundColor: '#EEF2FF',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  notifTypePillText: {
    color: '#31429B',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  notifAction: {
    color: '#666',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 2,
  },
  notifDetail: {
    color: '#4B5563',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 2,
  },
  notifTime: {
    color: '#A0A0A0',
    fontSize: 12,
    marginBottom: 8,
  },
  notifDeleteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    marginLeft: 10,
    marginTop: 2,
  },
  notifFollowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 4,
  },
  notifFollowButton: {
    minWidth: 78,
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifFollowAcceptButton: {
    backgroundColor: '#31429B',
  },
  notifFollowDeclineButton: {
    backgroundColor: '#FEE2E2',
  },
  notifFollowButtonText: {
    fontSize: 12,
    fontWeight: '800',
  },
  notifFollowAcceptButtonText: {
    color: '#FFFFFF',
  },
  notifFollowDeclineButtonText: {
    color: '#B91C1C',
  },
  sideMenuRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  sideMenuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  sideMenuContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '92%',
    maxWidth: 340,
    backgroundColor: '#F3F3F3',
    borderTopRightRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
  },
  sideMenuHeader: {
    backgroundColor: '#31429B',
    paddingHorizontal: 20,
    paddingTop: 54,
    paddingBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sideMenuTitle: {
    color: '#FFF',
    fontSize: 29,
    fontWeight: '700',
  },
  sideMenuAccent: {
    height: 5,
    backgroundColor: '#F2C919',
  },
  sideMenuBody: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  sideMenuFooter: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    paddingTop: 8,
    bottom: 30,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  signOutButton: {
    width: '76%',
    backgroundColor: '#FF1515',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  menuIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F2C919',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTextWrap: {
    marginLeft: 12,
    flex: 1,
  },
  menuItemTitle: {
    color: '#31429B',
    fontWeight: '700',
    fontSize: 16,
  },
  menuItemSub: {
    color: '#4A5FAE',
    fontSize: 10,
    fontStyle: 'italic',
    marginTop: 1,
  },
  signOutButtonText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: '700',
  },
});

export default styles;
