import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeAreaTop: { flex: 1, backgroundColor: "#F7F8FC" },
  container: { flex: 1, backgroundColor: "#F7F8FC" },
  mainScrollContent: {
    paddingBottom: 0,
    backgroundColor: "#F7F8FC",
  },
  homeContentShell: {
    paddingHorizontal: 20,
    paddingTop: 16,
    backgroundColor: "#F7F8FC",
  },
  greetingRow: {
    marginTop: 10,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileInfo: { flexDirection: "row", alignItems: "center" },
  avatarRingTouchable: { marginRight: 14 },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 8,
    borderWidth: 2.5,
  },
  profileTextWrap: { flexShrink: 1, justifyContent: "center" },
  greetingIntro: {
    color: "#7C879D",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 16,
    fontFamily: "Poppins_400Regular",
  },
  greetingName: {
    color: "#262C3F",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "900",
    marginTop: 2,
    maxWidth: 240,
    fontFamily: "Poppins_700Bold",
  },
  bellIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#FFD21F",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  bellIconInner: {
    position: "relative",
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: -6,
    right: -8,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#D92D20",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#FFD21F",
  },
  notificationBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "900",
    fontFamily: "Poppins_700Bold",
  },
  idSection: {
    marginTop: 4,
    marginBottom: 16,
    alignItems: "center",
  },
  idCardPerspective: {
    position: "relative",
    alignSelf: "center",
    borderRadius: 20,
    width: "100%",
    aspectRatio: 1.52, 
    perspective: 1000,
  },
  idCardFace: {
    ...StyleSheet.absoluteFillObject,
    backfaceVisibility: "hidden",
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  idCardFrontFace: { zIndex: 2 },
  idCardBackFace: { zIndex: 1 },
  idBackground: { width: "100%", height: "100%" },
  idBackgroundImage: { borderRadius: 24 },
  idPhoto: {
    position: "absolute",
    top: "13%",
    right: "2%",
    width: "30%",
    height: "58%",
    zIndex: 10,
  },
  idCardContent: {
    position: "absolute",
    top: "22%",
    left: "6%",
    width: "60%",
  },
  idName: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
    lineHeight: 20,
    marginTop: "20%",
    fontFamily: "Poppins_700Bold",
  },
  idCourse: {
    color: "#E2E8F0",
    fontSize: 12,
    marginTop: 4,
    fontWeight: "500",
    fontFamily: "Poppins_400Regular",
  },
  idClass: {
    color: "#E2E8F0",
    fontSize: 12,
    marginTop: 2,
    fontWeight: "700",
    fontFamily: "Poppins_600SemiBold",
  },
  idBackImage: { width: "100%", height: "100%", borderRadius: 24 },
  servicesSection: {
    marginTop: 20,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sectionHeaderTitle: {
    color: "#31429B",
    fontSize: 20,
    fontWeight: "900",
    fontFamily: "Poppins_700Bold",
  },
  sectionHeaderAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  sectionHeaderActionText: {
    color: "#31429B",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: "Poppins_600SemiBold",
  },
  servicesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 16,
  },
  serviceTile: {
    width: "31%",
    alignItems: "center",
  },
  serviceIconCircle: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  serviceLabel: {
    marginTop: 8,
    color: "#64748B",
    fontSize: 12,
    textAlign: "center",
    fontWeight: "600",
    fontFamily: "Poppins_600SemiBold",
  },

  // --- MAGIC CURVE ---
  curveContainer: {
    height: 50, 
    backgroundColor: "#31429B", 
    overflow: "hidden", 
    alignItems: "center",
    marginTop: 20, 
  },
  curveShape: {
    backgroundColor: "#F7F8FC", 
    position: "absolute",
    bottom: 0, 
    borderWidth: 14, 
    borderColor: "#F2C919",
  },

  newsSection: {
    backgroundColor: "#31429B",
    paddingTop: 12,
    paddingBottom: 24,
    overflow: "hidden",
  },
  newsTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "400",
    textAlign: "center",
    fontFamily: "Poppins",
  },
  newsTitleEmphasis: {
    fontStyle: "italic",
    fontWeight: "900",
    fontFamily: "Poppins_700Bold",
  },
  featuredScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
  },
  featuredEventCard: {
    width: 240,
    height: 250,
    borderRadius: 24,
    backgroundColor: "#0E173F",
    marginRight: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  featuredEventCardPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.95,
  },
  featuredEventImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#0E173F",
  },
  promoLoadingCard: {
    width: 240,
    height: 250,
    borderRadius: 24,
    marginRight: 16,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  promoLoadingText: {
    marginTop: 12,
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: "Poppins_600SemiBold",
  },
  promoEmptyCard: {
    width: 240,
    height: 250,
    borderRadius: 24,
    marginRight: 16,
    padding: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    justifyContent: "center",
    alignItems: "center",
  },
  promoEyebrow: {
    color: "#F2C919",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    fontFamily: "Poppins_700Bold",
  },
  promoTitleMain: {
    marginTop: 8,
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "600",
    textAlign: "center",
    fontFamily: "Poppins_600SemiBold",
  },

  // --- ALUMNI EXPLORER SECTION ---
  explorerSection: {
    position: "relative",
    alignItems: "center",
    paddingTop: 40,
    paddingBottom: 12,
    overflow: "hidden", 
  },
  dashedRing1: {
    position: "absolute",
    top: 60,
    width: 300,
    height: 300,
    borderRadius: 150,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    borderStyle: "dashed",
  },
  dashedRing2: {
    position: "absolute",
    top: -20,
    width: 460,
    height: 460,
    borderRadius: 230,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderStyle: "dashed",
  },
  dashedRing3: {
    position: "absolute",
    top: -100,
    width: 620,
    height: 620,
    borderRadius: 310,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderStyle: "dashed",
  },
  orb: {
    position: "absolute",
    borderRadius: 50,
  },
  orbGreenTop: { width: 14, height: 14, backgroundColor: "#4ADE80", top: 20, left: "25%" },
  orbGreyTopLeft: { width: 12, height: 12, backgroundColor: "#94A3B8", top: 65, left: "15%" },
  orbGreyTopRight: { width: 10, height: 10, backgroundColor: "#94A3B8", top: 15, right: "35%" },
  orbYellowLeft: { width: 22, height: 22, backgroundColor: "#F2C919", top: 160, left: -10 },
  orbGreenRight: { width: 12, height: 12, backgroundColor: "#4ADE80", top: 130, right: "12%" },
  orbYellowRight: { width: 18, height: 18, backgroundColor: "#F2C919", top: 220, right: "18%" },
  orbGreyBottomLeft: { width: 14, height: 14, backgroundColor: "#94A3B8", bottom: 120, left: "12%" },
  explorerTitle: {
    color: "#F2C919",
    fontSize: 48,
    lineHeight: 48,
    fontWeight: "1200",
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    fontFamily: "Poppins_700Bold",
  },
  explorerSubtitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "500",
    marginTop: 12,
    textAlign: "center",
    letterSpacing: 0,
    fontFamily: "Poppins_400Regular",
  },
  explorerStage: {
    marginTop: 60,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 30, 
  },
  explorerGhostCardLeft: {
    position: "absolute",
    left: -40, 
    width: 100,
    height: 240,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.9)",
    justifyContent: "center",
  },
  ghostOuterCircleLeft: {
    position: "absolute",
    left: -35,
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#FFFFFF",
  },
  explorerGhostCardRight: {
    position: "absolute",
    right: -40, 
    width: 100,
    height: 240,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.9)",
    justifyContent: "center",
  },
  ghostOuterCircleRight: {
    position: "absolute",
    right: -35,
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#FFFFFF",
  },
  explorerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 36,
    alignItems: "center",
    paddingHorizontal: 24,
    paddingBottom: 40, 
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
    position: "relative",
  },
  explorerCardPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.96,
  },
  explorerPhotoRing: {
    width: 180,
    height: 180,
    borderRadius: 90,
    marginTop: -90, 
    backgroundColor: "#FFFFFF",
    borderWidth: 10,
    borderColor: "#FFFFFF",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
    marginBottom: 16,
  },
  explorerPhoto: {
    width: "100%",
    height: "100%",
  },
  explorerCardTitle: {
    color: "#31429B",
    fontSize: 34,
    lineHeight: 36,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 12,
    fontFamily: "Poppins_700Bold",
  },
  explorerCardDescription: {
    color: "#31429B",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
    maxWidth: 240,
    fontWeight: "600",
    fontFamily: "Poppins_400Regular",
  },
  explorerArrowButton: {
    position: "absolute",
    bottom: -18, 
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#F2C919",
    borderWidth: 6,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },

  // --- MENU & MODALS ---
  sideMenuRoot: { flex: 1, flexDirection: "row" },
  sideMenuOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)" },
  sideMenuContainer: {
    position: "absolute", left: 0, top: 0, bottom: 0,
    backgroundColor: "#F9FAFB", borderTopRightRadius: 32, borderBottomRightRadius: 32,
  },
  sideMenuHeader: {
    backgroundColor: "#31429B", paddingHorizontal: 24, paddingTop: 60, paddingBottom: 24,
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
  },
  sideMenuTitle: { color: "#FFF", fontSize: 28, fontWeight: "800", fontFamily: "Poppins_700Bold" },
  sideMenuAccent: { height: 6, backgroundColor: "#F2C919" },
  sideMenuBody: { flex: 1, paddingHorizontal: 20, paddingTop: 24 },
  menuItem: { flexDirection: "row", alignItems: "center", marginBottom: 24 },
  menuIconCircle: {
    width: 44, height: 44, borderRadius: 22, backgroundColor: "#F2C919",
    alignItems: "center", justifyContent: "center",
  },
  menuTextWrap: { marginLeft: 16, flex: 1 },
  menuItemTitle: { color: "#31429B", fontWeight: "800", fontSize: 16, fontFamily: "Poppins_700Bold" },
  menuItemSub: { color: "#64748B", fontSize: 11, marginTop: 2, fontWeight: "500", fontFamily: "Poppins_400Regular" },
  sideMenuFooter: { padding: 24, alignItems: "center" },
  signOutButton: {
    width: "80%", backgroundColor: "#EF4444", borderRadius: 16,
    paddingVertical: 14, alignItems: "center",
    shadowColor: "#EF4444", shadowOpacity: 0.3, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }
  },
  signOutButtonText: { color: "#FFF", fontSize: 16, fontWeight: "800", fontFamily: "Poppins_700Bold" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0, 0, 0, 0.4)", justifyContent: "flex-start", alignItems: "flex-end" },
  modalSideContainer: { backgroundColor: "#F9FAFB", position: "absolute", right: 0, top: 0, bottom: 0, borderTopLeftRadius: 32, borderBottomLeftRadius: 32 },
  modalHeader: { backgroundColor: "#31429B", flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 20, paddingHorizontal: 24, paddingTop: 60 },
  modalTitle: { color: "#FFF", fontSize: 20, fontWeight: "800", fontFamily: "Poppins_700Bold" },
  modalAccentLine: { height: 6, backgroundColor: "#F2C919" },
  notifList: { padding: 24, flexGrow: 1 },
  notifCard: { flexDirection: "row", marginBottom: 28, alignItems: "flex-start" },
  notifAvatar: { width: 48, height: 48, borderRadius: 24, borderWidth: 2, borderColor: "#F2C919", marginRight: 16 },
  notifBody: { flex: 1 },
  notifName: { color: "#31429B", fontWeight: "800", fontSize: 15, lineHeight: 20, fontFamily: "Poppins_700Bold" },
  notifAction: { color: "#475569", fontSize: 13, lineHeight: 18, marginBottom: 4, fontFamily: "Poppins_400Regular" },
  notifDetail: { color: "#64748B", fontSize: 12, lineHeight: 16, marginBottom: 4, fontFamily: "Poppins_400Regular" },
  notifTime: { color: "#94A3B8", fontSize: 11, fontWeight: "600", fontFamily: "Poppins_400Regular" },
  notifDeleteButton: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#FEE2E2", marginLeft: 12 },
});

export default styles;