import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeAreaTop: { flex: 1, backgroundColor: "#F7F8FC" },
  container: { flex: 1, backgroundColor: "#F7F8FC" },
  mainScrollContent: {
    paddingBottom: 28,
    backgroundColor: "#F7F8FC",
  },
  homeContentShell: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: "#F7F8FC",
  },
  homeTopCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.07,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  homeTopCardBody: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 22,
    paddingVertical: 16,
  },
  homeTopLeftLogo: {
    maxWidth: 122,
  },
  homeTopRightLogo: {
    maxWidth: 156,
  },
  greetingRow: {
    marginTop: 20,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  greetingIntro: {
    color: "#7C879D",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 18,
  },
  greetingName: {
    color: "#262C3F",
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "900",
    marginTop: 2,
    maxWidth: 250,
  },
  bellIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFD21F",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  bellIconInner: {
    position: "relative",
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: -7,
    right: -8,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#D92D20",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  notificationBadgeText: {
    color: "#F9FAFB",
    fontSize: 9,
    fontWeight: "800",
    lineHeight: 10,
  },
  servicesSection: {
    marginTop: 16,
    paddingTop: 6,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionHeaderTitle: {
    color: "#33499B",
    fontSize: 19,
    fontWeight: "900",
  },
  sectionHeaderAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  sectionHeaderActionText: {
    color: "#33499B",
    fontSize: 14,
    fontWeight: "500",
  },
  servicesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 14,
  },
  serviceTile: {
    width: "31%",
    alignItems: "center",
  },
  serviceIconCircle: {
    width: 98,
    height: 98,
    borderRadius: 49,
    backgroundColor: "#EFEFEF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.02,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 0,
  },
  serviceLabel: {
    marginTop: 10,
    color: "#8C8C8C",
    fontSize: 12,
    lineHeight: 16,
    textAlign: "center",
    fontWeight: "500",
  },
  idSection: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    marginTop: 10,
    marginBottom: 6,
  },
  idCardPerspective: {
    position: "relative",
    alignSelf: "center",
    borderRadius: 24,
    overflow: "visible",
    perspective: 1000,
  },
  newsSection: {
    marginTop: 4,
    backgroundColor: "#36479B",
    paddingTop: 36,
    paddingBottom: 20,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: "hidden",
  },
  newsCurve: {
    position: "absolute",
    top: -16,
    left: -40,
    right: -40,
    height: 48,
    backgroundColor: "#F2C919",
    borderBottomLeftRadius: 999,
    borderBottomRightRadius: 999,
  },
  newsTitle: {
    color: "#FFFFFF",
    fontSize: 29,
    lineHeight: 33,
    fontWeight: "800",
    textAlign: "center",
  },
  newsTitleEmphasis: {
    fontStyle: "italic",
    fontWeight: "900",
  },
  featuredScrollContent: {
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 24,
  },
  featuredEventCard: {
    width: 210,
    height: 218,
    borderRadius: 18,
    backgroundColor: "#0E173F",
    marginRight: 14,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  featuredEventCardPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.92,
  },
  featuredEventImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#0E173F",
  },
  promoLoadingCard: {
    width: 210,
    height: 218,
    borderRadius: 18,
    marginRight: 14,
    backgroundColor: "#F7FAFF",
    alignItems: "center",
    justifyContent: "center",
  },
  promoLoadingText: {
    marginTop: 10,
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  promoEmptyCard: {
    width: 210,
    height: 218,
    borderRadius: 18,
    marginRight: 14,
    padding: 14,
    backgroundColor: "#EEF2FF",
    justifyContent: "center",
  },
  promoEyebrow: {
    color: "#33499B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.9,
  },
  promoTitleMain: {
    marginTop: 8,
    color: "#33499B",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
  explorerSection: {
    position: "relative",
    alignItems: "center",
    paddingTop: 22,
    paddingBottom: 8,
  },
  explorerOrbLarge: {
    position: "absolute",
    top: 48,
    left: -10,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#F2C919",
  },
  explorerOrbSmallLeft: {
    position: "absolute",
    top: 16,
    left: 56,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#6EC6FF",
    opacity: 0.85,
  },
  explorerOrbSmallRight: {
    position: "absolute",
    top: 24,
    right: 52,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#C6D1FF",
    opacity: 0.9,
  },
  explorerTitle: {
    color: "#F2C919",
    fontSize: 38,
    lineHeight: 38,
    fontWeight: "900",
    textAlign: "center",
  },
  explorerSubtitle: {
    color: "#FFFFFF",
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "800",
    marginTop: 10,
    textAlign: "center",
  },
  explorerStage: {
    marginTop: 32,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  explorerGhostCardLeft: {
    position: "absolute",
    left: -22,
    width: 88,
    height: 176,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.94)",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  explorerGhostCardRight: {
    position: "absolute",
    right: -22,
    width: 88,
    height: 176,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.94)",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  explorerCard: {
    backgroundColor: "#F8FAFF",
    borderRadius: 32,
    alignItems: "center",
    paddingTop: 16,
    paddingHorizontal: 22,
    paddingBottom: 22,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
  explorerCardPressed: {
    transform: [{ scale: 0.99 }],
    opacity: 0.94,
  },
  explorerPhotoRing: {
    width: 150,
    height: 150,
    borderRadius: 75,
    marginTop: -82,
    backgroundColor: "#FFFFFF",
    borderWidth: 8,
    borderColor: "#FFFFFF",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  explorerPhoto: {
    width: "100%",
    height: "100%",
  },
  explorerCardTitle: {
    marginTop: 14,
    color: "#33499B",
    fontSize: 26,
    lineHeight: 28,
    fontWeight: "900",
    textAlign: "center",
  },
  explorerCardDescription: {
    marginTop: 6,
    color: "#33499B",
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
    maxWidth: 220,
  },
  explorerArrowButton: {
    marginTop: 20,
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#F2C919",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  bottomSpacer: {
    height: 16,
  },
  brandHeader: {
    backgroundColor: "#31429B",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.12)",
  },
  brandRow: {
    backgroundColor: "#31429B",
    paddingHorizontal: 0,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brandAccent: {
    height: 10,
    backgroundColor: "#F2C919",
    width: "100%",
  },
  brandLogo: {
    width: 136,
    height: 42,
  },
  nulipaPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    minWidth: 122,
    justifyContent: "center",
  },
  nulipaIcon: {
    width: 22,
    height: 22,
    marginRight: 6,
  },
  nulipaText: {
    color: "#31429B",
    fontWeight: "800",
    fontSize: 14,
    letterSpacing: 0.3,
  },
  profileSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingTop: 12,
    paddingBottom: 5,
    alignItems: "center",
  },
  profileInfo: { flexDirection: "row", alignItems: "center" },
  avatarRingTouchable: { marginRight: 12 },
  profileTextWrap: { flexShrink: 1, marginLeft: -20 },
  nameRow: { flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    borderWidth: 2,
    borderColor: "#F2C919",
  },
  greeting: { fontSize: 17, fontWeight: "800", color: "#0A1142" },
  badge: { marginLeft: 6 },
  studentId: { fontSize: 10, color: "#666", marginTop: 1 },
  profileStrengthText: { fontSize: 10, color: "#6B7280", marginTop: 3 },
  statusHighlight: { color: "#F59E0B", fontWeight: "800" },
  statusComplete: { color: "#10B981", fontWeight: "800" },
  bellIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFD21F",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  bellIconInner: {
    position: "relative",
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: -7,
    right: -8,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#D92D20",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  notificationBadgeText: {
    color: "#F9FAFB",
    fontSize: 9,
    fontWeight: "800",
    lineHeight: 10,
  },
  idSection: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    marginTop: 10,
    marginBottom: 6,
  },
  profileCardWrapper: {
    marginTop: -8,
    backgroundColor: "#F9FAFB",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5EAFB",
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    marginBottom: 18,
  },
  tabRow: {
    flexDirection: "row",
    marginBottom: -10,
    zIndex: 1,
    marginLeft: 15,
  },
  activeTab: {
    backgroundColor: "#F2C919",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  activeTabText: { color: "#31429B", fontWeight: "bold" },
  inactiveTab: {
    backgroundColor: "#E0E0E0",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    marginLeft: 10,
  },
  inactiveTabText: { color: "#666" },
  idCard: {
    borderRadius: 14,
    overflow: "hidden",
    elevation: 6,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    backgroundColor: "#0A1142",
    width: "92%", // Take up most of the screen width
    aspectRatio: 1.58, // This is the "Magic Ratio" for IDs
    alignSelf: "center",
  },
  idCardPerspective: {
    position: "relative",
    alignSelf: "center",
    borderRadius: 24,
    overflow: "visible",
    perspective: 1000,
  },
  idCardFace: {
    ...StyleSheet.absoluteFillObject,
    backfaceVisibility: "hidden",
    borderRadius: 24,
    overflow: "hidden",
  },
  idCardFrontFace: {
    zIndex: 2,
  },
  idCardBackFace: {
    zIndex: 1,
  },
  idBackground: {
    width: "100%",
    height: "100%",
    flex: 1,
    justifyContent: "flex-end",
    borderRadius: 24,
    overflow: "hidden",
  },
  idBackgroundImage: {
    width: "100%",
    height: "100%",
    borderRadius: 24,
  },
  idPhoto: {
    position: "absolute",
    top: 28,
    right: 6,
    width: 106,
    height: 126,
    zIndex: 10,
  },
  idCardContent: {
    position: "absolute",
    top: 46,
    left: 20,
    bottom: 22,
    width: 206,
    justifyContent: "flex-start", //
  },
  idName: {
    color: "#F9FAFB",
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 18,
    marginTop: 44,
  },
  idCourse: {
    color: "#F9FAFB",
    fontSize: 12,
    marginTop: 6,
  },
  idClass: {
    color: "#F9FAFB",
    fontSize: 12,
    marginTop: 2,
  },
  idBackImage: {
    width: "100%",
    height: "100%",
    borderRadius: 24,
  },
  sectionContainer: { marginBottom: 0 },
  sectionInset: { marginLeft: 0, marginRight: 0 },
  sectionNudgeRight: { transform: [{ translateX: 0 }] },
  quickLinksSection: { marginTop: 8, marginBottom: 12, paddingBottom: 8 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#31429B",
    marginBottom: 8,
    left: 10,
  },
  horizontalScroll: { flexDirection: "row" },
  horizontalScrollContent: {
    paddingBottom: 8,
  },
  featuredEventCard: {
    width: 214,
    height: 220,
    borderRadius: 20,
    backgroundColor: "#0E173F",
    marginRight: 14,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  featuredEventCardPressed: {
    transform: [{ scale: 0.985 }],
    opacity: 0.92,
  },
  featuredEventImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#0E173F",
  },
  featuredEventBody: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
  },
  cardBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardBadge: {
    width: 58,
    height: 14,
    borderRadius: 999,
    backgroundColor: "rgba(49, 66, 155, 0.14)",
  },
  cardBadgeShort: {
    width: 44,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(49, 66, 155, 0.1)",
  },
  cardButtonPill: {
    width: 92,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#F2C919",
    alignItems: "center",
    justifyContent: "center",
  },
  featuredEventTitle: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "800",
    color: "#31429B",
  },
  featuredEventDescription: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 16,
    color: "#4B5563",
  },
  featuredEventMetaRow: {
    top: 3,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  featuredEventMetaText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 14,
    color: "#6B7280",
    fontWeight: "700",
  },
  cardButtonPillText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#31429B",
  },
  promoLoadingCard: {
    width: 214,
    height: 220,
    borderRadius: 20,
    marginRight: 14,
    backgroundColor: "#F7FAFF",
    alignItems: "center",
    justifyContent: "center",
  },
  promoLoadingText: {
    marginTop: 10,
    color: "#33499B",
    fontSize: 12,
    fontWeight: "700",
  },
  promoEmptyCard: {
    width: 214,
    height: 220,
    borderRadius: 20,
    marginRight: 14,
    padding: 14,
    backgroundColor: "#EEF2FF",
    justifyContent: "center",
  },
  quickLinksRow: { flexDirection: "row", justifyContent: "space-between" },
  quickLinksScrollContent: {
    paddingBottom: 8,
  },
  quickLinkBox: {
    width: 192,
    minHeight: 64,
    backgroundColor: "#F9FAFB",
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    left: 10,
  },
  quickLinkText: {
    marginLeft: 12,
    color: "#31429B",
    fontWeight: "800",
    fontSize: 14,
    lineHeight: 18,
  },
  quickLinkIcon: {
    width: 36,
    height: 36,
  },
  quickLinkIconNU: {
    width: 26,
    height: 26,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "flex-start",
    alignItems: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#FFF",
    height: "85%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: "hidden",
    marginTop: 50,
  },
  modalSideContainer: {
    backgroundColor: "#FFF",
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: "100%",
    borderTopLeftRadius: 28,
    borderBottomLeftRadius: 28,
    overflow: "hidden",
  },
  modalHeader: {
    backgroundColor: "#31429B",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  modalTitle: {
    color: "#FFF",
    fontSize: 20,
    fontWeight: "bold",
  },
  modalHeaderSpacer: {
    width: 28,
  },
  closeBtn: { padding: 5 },
  modalAccentLine: {
    height: 5,
    backgroundColor: "#F2C919",
  },
  notifList: {
    padding: 20,
    flexGrow: 1,
  },
  emptyNotifWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 30,
  },
  emptyNotifText: {
    color: "#666",
    fontSize: 14,
  },
  notifCard: {
    flexDirection: "row",
    marginBottom: 25,
    alignItems: "flex-start",
    paddingRight: 2,
  },
  notifAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "#F2C919",
    marginRight: 15,
  },
  notifBody: {
    flex: 1,
  },
  notifTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  notifName: {
    color: "#31429B",
    fontWeight: "bold",
    fontSize: 14,
    lineHeight: 20,
  },
  notifTypePill: {
    backgroundColor: "#EEF2FF",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  notifTypePillText: {
    color: "#31429B",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  notifAction: {
    color: "#666",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 2,
  },
  notifDetail: {
    color: "#4B5563",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 2,
  },
  notifTime: {
    color: "#A0A0A0",
    fontSize: 12,
    marginBottom: 8,
  },
  notifDeleteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEE2E2",
    marginLeft: 10,
    marginTop: 2,
  },
  notifFollowActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
    marginBottom: 4,
  },
  notifFollowButton: {
    minWidth: 78,
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  notifFollowAcceptButton: {
    backgroundColor: "#31429B",
  },
  notifFollowDeclineButton: {
    backgroundColor: "#FEE2E2",
  },
  notifFollowButtonText: {
    fontSize: 12,
    fontWeight: "800",
  },
  notifFollowAcceptButtonText: {
    color: "#F9FAFB",
  },
  notifFollowDeclineButtonText: {
    color: "#B91C1C",
  },
  sideMenuRoot: {
    flex: 1,
    flexDirection: "row",
  },
  sideMenuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  sideMenuContainer: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "92%",
    maxWidth: 340,
    backgroundColor: "#F3F3F3",
    borderTopRightRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  sideMenuHeader: {
    backgroundColor: "#31429B",
    paddingHorizontal: 20,
    paddingTop: 54,
    paddingBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sideMenuTitle: {
    color: "#FFF",
    fontSize: 29,
    fontWeight: "700",
  },
  sideMenuAccent: {
    height: 5,
    backgroundColor: "#F2C919",
  },
  sideMenuBody: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  sideMenuFooter: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    paddingTop: 8,
    bottom: 30,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  signOutButton: {
    width: "76%",
    backgroundColor: "#FF1515",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  menuIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F2C919",
    alignItems: "center",
    justifyContent: "center",
  },
  menuTextWrap: {
    marginLeft: 12,
    flex: 1,
  },
  menuItemTitle: {
    color: "#31429B",
    fontWeight: "700",
    fontSize: 16,
  },
  menuItemSub: {
    color: "#4A5FAE",
    fontSize: 10,
    fontStyle: "italic",
    marginTop: 1,
  },
  signOutButtonText: {
    color: "#FFF",
    fontSize: 17,
    fontWeight: "700",
  },
});

export default styles;
