import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E5B80B",
    paddingVertical: 24,
  },
  cardContainer: {
    backgroundColor: "#31429B",
    width: "88%",
    maxWidth: 420,
    borderRadius: 26,
    padding: 28,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    elevation: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
  },
  logo: {
    width: "100%",
    height: 69,
    marginBottom: 28,
  },
  label: {
    color: "#F9FAFB",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D7DDF0",
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 14,
    marginBottom: 20,
    color: "#333",
    minHeight: 50,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D7DDF0",
    marginBottom: 15,
    minHeight: 50,
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 14,
    color: "#333",
  },
  eyeIcon: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  optionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 30,
  },
  rememberContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: "#F2C919",
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  checkboxChecked: {
    backgroundColor: "#F2C919",
  },
  optionText: {
    color: "#F9FAFB",
    fontSize: 12,
  },
  button: {
    backgroundColor: "#F2C919",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 25,
    minHeight: 50,
    shadowColor: "#1F2A64",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  buttonText: {
    color: "#31429B",
    fontSize: 18,
    fontWeight: "bold",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 2,
  },
  footerText: {
    color: "#E0E0E0",
    fontSize: 13,
  },
  signUpText: {
    color: "#F9FAFB",
    fontSize: 13,
    fontWeight: "bold",
  },
});

export default styles;
