import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#31429B",
  },
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  content: {
    flexGrow: 1,
    paddingBottom: 18,
    backgroundColor: "#F9FAFB",
  },
  backButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#384A9C",
    alignItems: "center",
    justifyContent: "center",
  },
  heroBackRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  heroCard: {
    marginTop: 0,
    marginHorizontal: 0,
    backgroundColor: "#F9FAFB",
    borderBottomLeftRadius: 38,
    borderBottomRightRadius: 38,
    padding: 16,
    marginBottom: -24,
    position: "relative",
    zIndex: 2,
    shadowColor: "#1F2937",
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  heroTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  heroRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatar: {
    backgroundColor: "#E5E7EB",
    marginRight: 14,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
  },
  name: {
    flex: 1,
    paddingRight: 8,
    color: "#384A9C",
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "900",
  },
  tagPill: {
    marginTop: 8,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#FFD84D",
  },
  tagText: {
    marginLeft: 4,
    color: "#31429B",
    fontSize: 11,
    fontWeight: "800",
  },
  statsRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  heroActionsRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  addConnectionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#31429B",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  removeConnectionButton: {
    backgroundColor: "#B42318",
  },
  pendingConnectionButton: {
    backgroundColor: "#7C3AED",
  },
  addConnectionButtonDisabled: {
    backgroundColor: "#6B7280",
  },
  addConnectionButtonText: {
    color: "#F9FAFB",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  messageButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#C7D2FE",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  messageButtonDisabled: {
    backgroundColor: "#F3F4F6",
    borderColor: "#E5E7EB",
  },
  messageButtonText: {
    color: "#31429B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  statBlock: {
    minWidth: 64,
    alignItems: "center",
    marginHorizontal: 4,
  },
  statValue: {
    fontSize: 24,
    lineHeight: 26,
    color: "#30343C",
    fontWeight: "500",
  },
  statLabel: {
    marginTop: 2,
    color: "#5C6471",
    fontSize: 12,
    textAlign: "center",
  },
  sectionBlock: {
    marginTop: 18,
    paddingHorizontal: 0,
  },
  postsSectionBlock: {
    marginTop: 18,
    paddingHorizontal: 10,
  },
  postsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  createPostButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backgroundColor: "#31429B",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  createPostButtonText: {
    color: "#F9FAFB",
    fontSize: 12,
    fontWeight: "800",
  },
  aboutSectionWrap: {
    marginTop: 20,
    paddingHorizontal: 0,
    position: "relative",
    zIndex: 1,
  },
  aboutSectionCard: {
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 14,
    paddingTop: 32,
    paddingBottom: 12,
    minHeight: 150,
    shadowColor: "#1F2937",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  bioSectionCard: {
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 12,
    minHeight: 150,
    borderRadius: 22,
    shadowColor: "#1F2937",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workSectionCard: {
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 12,
    borderRadius: 22,
    shadowColor: "#1F2937",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workPagerContent: {
    alignItems: "stretch",
    marginBottom: 12,
  },
  workPage: {
    paddingRight: 12,
  },
  sectionHeading: {
    color: "#404040",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  aboutItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 6,
    marginBottom: 6,
  },
  aboutText: {
    marginLeft: 8,
    color: "#404040",
    fontSize: 14,
  },
  biographyText: {
    color: "#404040",
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: 6,
  },
  workCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 10,
    shadowColor: "#1F2937",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  workRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  workNavButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9FAFB",
    shadowColor: "#1F2937",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workContent: {
    flex: 1,
    paddingHorizontal: 10,
  },
  workTitleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  workTitle: {
    marginLeft: 6,
    color: "#30343C",
    fontSize: 15,
    fontWeight: "800",
  },
  workSubtitle: {
    marginTop: 2,
    color: "#31429B",
    fontSize: 12,
    fontWeight: "600",
  },
  workPeriod: {
    marginTop: 10,
    color: "#5C6471",
    fontSize: 12,
  },
  workLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  workLocation: {
    marginLeft: 6,
    color: "#5C6471",
    fontSize: 12,
  },
  workDescription: {
    marginTop: 10,
    color: "#404040",
    fontSize: 12,
    lineHeight: 18,
  },
  paginationRow: {
    marginTop: 10,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  paginationDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    marginHorizontal: 3,
    backgroundColor: "#D9DCE3",
  },
  paginationDotActive: {
    width: 18,
    backgroundColor: "#31429B",
  },
  postsCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 22,
    padding: 16,
    minHeight: 84,
  },
  profilePostItem: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  profilePostHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 8,
  },
  profilePostTypePill: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    gap: 4,
  },
  profilePostPill: {
    backgroundColor: "#EEF2FF",
  },
  profileRepostPill: {
    backgroundColor: "#DCFCE7",
  },
  profilePostTypeText: {
    color: "#31429B",
    fontSize: 11,
    fontWeight: "800",
  },
  profileRepostTypeText: {
    color: "#15803D",
  },
  profilePostTime: {
    flex: 1,
    textAlign: "right",
    color: "#7A869A",
    fontSize: 10,
    fontWeight: "700",
  },
  profilePostCaption: {
    color: "#334155",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  profileOriginalWrap: {
    borderWidth: 1,
    borderColor: "#DCE3F5",
    borderRadius: 10,
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  profileOriginalLabel: {
    color: "#475569",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 4,
  },
  profileOriginalCaption: {
    color: "#334155",
    fontSize: 12,
    lineHeight: 17,
  },
  profilePostImagesGrid: {
    marginBottom: 8,
    gap: 8,
  },
  profilePostImagesRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  profilePostImageTile: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#E2E8F0",
  },
  profilePostImageTileWithGap: {
    marginRight: 8,
  },
  profilePostImageTileSpacer: {
    flex: 1,
  },
  profilePostImageTileSingle: {
    flex: 0,
    width: "100%",
    aspectRatio: 1.2,
  },
  profilePostImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#E2E8F0",
  },
  profilePostImageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.45)",
  },
  profilePostImageOverlayText: {
    color: "#F9FAFB",
    fontSize: 20,
    fontWeight: "900",
  },
  profilePostMetricsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profilePostMetricText: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "700",
  },
  emptyPostsText: {
    color: "#8A8F9A",
    fontSize: 13,
  },
  postsLoadingWrap: {
    minHeight: 84,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  postsLoadingText: {
    color: "#31429B",
    fontSize: 12,
    fontWeight: "700",
  },
  stateWrap: {
    minHeight: 420,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingHorizontal: 20,
  },
  errorText: {
    color: "#B91C1C",
    textAlign: "center",
    fontSize: 15,
  },
  actionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: "#31429B",
    borderRadius: 14,
  },
  actionButtonText: {
    color: "#F9FAFB",
    fontSize: 14,
    fontWeight: "700",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 28,
  },
  emptyStateText: {
    color: "#8A8F9A",
    marginTop: 10,
    fontSize: 13,
  },
});

export default styles;
