import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(50, 65, 140, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  cardContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    width: width * 0.92,
    maxWidth: 420,
    maxHeight: height * 0.88,
    padding: 28,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 25,
    elevation: 10,
  },
  scrollContent: {
    alignItems: "center",
    paddingVertical: 8,
  },
  iconContainer: {
    marginBottom: 20,
  },
  iconWrapper: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: "#E8EBF7",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontFamily: "Poppins-ExtraBold",
    fontSize: 20,
    color: "#32418C",
    marginBottom: 8,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: "#6B7280",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 24,
    fontFamily: "Poppins-Regular", // or "Poppins-Regular"
  },
  messageCard: {
    flexDirection: "row",
    backgroundColor: "#EFF6FF",
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#3b82f6",
    marginBottom: 20,
    width: "100%",
    alignItems: "flex-start",
    gap: 12,
  },
  messageText: {
    flex: 1,
    fontSize: 15,
    color: "#1E293B",
    lineHeight: 22,
    fontWeight: "500",
    fontFamily: "Poppins_500Medium",
  },
  infoBox: {
    flexDirection: "row",
    backgroundColor: "#FEF3C7",
    padding: 14,
    borderRadius: 12,
    gap: 12,
    marginBottom: 24,
    width: "100%",
    alignItems: "flex-start",
  },
  infoText: {
    flex: 1,
    fontSize: 14,
    color: "#92400E",
    lineHeight: 20,
    fontFamily: "Poppins_400Regular",
  },
  contactButton: {
    flexDirection: "row",
    backgroundColor: "#32418C",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    width: "100%",
    marginBottom: 12,
    shadowColor: "#32418C",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  contactButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Poppins_600SemiBold",
  },
  logoutButton: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    width: "100%",
    marginBottom: 16,
  },
  logoutButtonText: {
    color: "#6B7280",
    fontSize: 16,
    fontWeight: "500",
    fontFamily: "Poppins_500Medium",
  },
  footerText: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 8,
    letterSpacing: 0.5,
    fontFamily: "Poppins_400Regular",
  },
});