import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  topSafe: { backgroundColor: '#31429B' },
  bottomSafe: { backgroundColor: '#F9FAFB' },
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  header: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  backButton: {
    minWidth: 72,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  backButtonText: {
    fontSize: 15,
    color: '#31429B',
    fontWeight: '700',
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  headerSpacer: {
    width: 72,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 6,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#31429B',
    borderRadius: 6,
  },
  wizardScroll: {
    flex: 1,
  },
  content: { padding: 16, paddingBottom: 24 },
  headerImage: { width: '100%', height: 180, resizeMode: 'cover', borderRadius: 12 },
  titleCard: {
    marginTop: -36,
    marginBottom: 20,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 14,
    alignSelf: 'stretch',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  titleText: { fontSize: 18, fontWeight: '800', color: '#24346F' },
  formDescriptionText: {
    marginTop: 8,
    fontSize: 13,
    color: '#4B5563',
    lineHeight: 18,
  },
  card: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    marginBottom: 12,
  },
  screenCard: {
    marginTop: 8,
    minHeight: 220,
  },
  cardInvalid: {
    borderColor: '#D14343',
  },
  questionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  requiredMark: {
    marginLeft: 6,
    color: '#D14343',
    fontSize: 18,
    fontWeight: '700',
  },
  cardTitle: { fontSize: 16, fontWeight: '700', color: '#24346F', marginBottom: 8 },
  cardText: { fontSize: 14, color: '#374151', lineHeight: 20 },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 6,
  },
  optionRowActive: {
    backgroundColor: '#EEF4FF',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxOuter: {
    borderRadius: 5,
  },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#31429B' },
  checkboxInner: {
    borderRadius: 2,
  },
  optionText: { fontSize: 14, color: '#374151' },
  textInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#111827',
    backgroundColor: '#F9FAFB',
    marginTop: 6,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  requiredHint: {
    color: '#D14343',
    fontSize: 12,
    marginTop: 8,
  },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  nextButton: {
    backgroundColor: '#31429B',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  nextButtonDisabled: {
    opacity: 0.7,
  },
  nextButtonText: {
    color: '#F9FAFB',
    fontWeight: '700',
    fontSize: 16,
  },
});

export default styles;
