import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFFFF' },
  topSafe: { backgroundColor: '#31429B' },
  bottomSafe: { backgroundColor: '#FFFFFF' },
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  content: { padding: 16, paddingBottom: 32 },
  backRow: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 2 },
  backButton: { alignSelf: 'flex-start', paddingVertical: 4, paddingHorizontal: 2 },
  backButtonText: { fontSize: 15, color: '#31429B', fontWeight: '600' },
  headerImage: { width: '100%', height: 180, resizeMode: 'cover', borderRadius: 12 },
  titleCard: {
    marginTop: -36,
    marginBottom: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    alignSelf: 'stretch',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  titleText: { fontSize: 18, fontWeight: '800', color: '#24346F' },
  sectionLabel: { fontSize: 13, color: '#6B7280', marginTop: 16, marginBottom: 8 },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    marginBottom: 12,
  },
  cardInvalid: {
    borderColor: '#D14343',
  },
  questionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  requiredMark: {
    marginLeft: 6,
    color: '#D14343',
    fontSize: 18,
    fontWeight: '700',
  },
  cardTitle: { fontSize: 16, fontWeight: '700', color: '#24346F', marginBottom: 8 },
  cardText: { fontSize: 14, color: '#374151', lineHeight: 20 },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 6,
  },
  optionRowActive: {
    backgroundColor: '#EEF4FF',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxOuter: {
    borderRadius: 5,
  },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#31429B' },
  checkboxInner: {
    borderRadius: 2,
  },
  optionText: { fontSize: 14, color: '#374151' },
  textInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#111827',
    backgroundColor: '#FFFFFF',
    marginTop: 6,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  requiredHint: {
    color: '#D14343',
    fontSize: 12,
    marginTop: 8,
  },
  submitButton: {
    marginTop: 18,
    backgroundColor: '#F2C919',
    paddingVertical: 14,
    borderRadius: 28,
    alignItems: 'center',
  },
  submitText: { color: '#24346F', fontWeight: '700', fontSize: 16 },
});

export default styles;
