import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F5F6FA',
	},
	content: {
		paddingBottom: 24,
	},
	searchRow: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 16,
		paddingVertical: 18,
		backgroundColor: '#F9FAFB',
		borderBottomWidth: 1,
		borderBottomColor: '#D9D9D9',
	},
	searchAvatar: {
		width: 34,
		height: 34,
		borderRadius: 17,
		marginRight: 10,
		backgroundColor: '#E5E7EB',
	},
	searchWrap: {
		flex: 1,
		height: 40,
		borderRadius: 999,
		backgroundColor: '#F1F1F1',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingLeft: 18,
		paddingRight: 14,
	},
	searchInput: {
		flex: 1,
		fontSize: 15,
		color: '#5A5A5A',
		paddingVertical: 0,
		paddingRight: 10,
	},
	searchResultsContainer: {
		maxHeight: 500,
		backgroundColor: '#F9FAFB',
		borderBottomWidth: 1,
		borderBottomColor: '#D9D9D9',
		paddingHorizontal: 16,
		paddingVertical: 12,
	},
	searchLoadingContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 20,
		gap: 10,
	},
	searchLoadingText: {
		fontSize: 14,
		color: '#7A7A7A',
	},
	noResultsText: {
		fontSize: 14,
		color: '#7A7A7A',
		textAlign: 'center',
		paddingVertical: 20,
	},
	searchResultItem: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingVertical: 12,
		paddingHorizontal: 8,
		borderBottomWidth: 1,
		borderBottomColor: '#F0F0F0',
	},
	searchResultAvatar: {
		width: 40,
		height: 40,
		borderRadius: 20,
		marginRight: 12,
		backgroundColor: '#E5E7EB',
	},
	searchResultInfo: {
		flex: 1,
	},
	searchResultName: {
		fontSize: 14,
		fontWeight: '600',
		color: '#31429B',
	},
	createPostCard: {
		marginHorizontal: 6,
		marginTop: 10,
		backgroundColor: '#F9FAFB',
		borderRadius: 18,
		borderWidth: 1,
		borderColor: '#DCDDE4',
		paddingHorizontal: 18,
		paddingTop: 16,
		paddingBottom: 18,
	},
	createPostTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
		marginBottom: 12,
	},
	composeRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 10,
	},
	composeBubble: {
		flex: 1,
		minHeight: 46,
		borderRadius: 999,
		backgroundColor: '#F4C91B',
		flexDirection: 'row',
		alignItems: 'center',
		paddingLeft: 10,
		paddingRight: 14,
	},
	composeAvatar: {
		width: 28,
		height: 28,
		borderRadius: 14,
		marginRight: 10,
		backgroundColor: '#E5E7EB',
	},
	composePrompt: {
		flex: 1,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '700',
		color: '#31429B',
	},
	sendButton: {
		marginLeft: 12,
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: 'center',
		justifyContent: 'center',
	},
	actionRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
		flexWrap: 'wrap',
	},
	actionChip: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#F0EDF6',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 6,
	},
	actionChipText: {
		marginLeft: 6,
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '700',
		color: '#4C4F87',
	},
	feedSection: {
		paddingHorizontal: 6,
		paddingTop: 16,
	},
	feedHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 10,
		paddingHorizontal: 6,
	},
	feedTitle: {
		fontSize: 16,
		fontWeight: '800',
		color: '#24346F',
	},
	feedCount: {
		fontSize: 12,
		fontWeight: '700',
		color: '#8A94A6',
	},
	feedStateCard: {
		backgroundColor: '#F9FAFB',
		borderRadius: 18,
		paddingVertical: 18,
		paddingHorizontal: 16,
		alignItems: 'center',
		justifyContent: 'center',
		gap: 10,
		marginBottom: 12,
	},
	feedStateText: {
		fontSize: 13,
		color: '#5A5A5A',
		fontWeight: '600',
		textAlign: 'center',
	},
	postCard: {
		backgroundColor: '#F9FAFB',
		borderRadius: 20,
		borderWidth: 0,
		paddingHorizontal: 14,
		paddingTop: 14,
		paddingBottom: 12,
		marginBottom: 14,
		marginHorizontal: 6,
		shadowColor: '#111827',
		shadowOpacity: 0.08,
		shadowRadius: 14,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	postHeader: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		marginBottom: 10,
	},
	postAvatar: {
		width: 38,
		height: 38,
		borderRadius: 19,
		backgroundColor: '#E5E7EB',
		marginRight: 10,
	},
	announcementAvatar: {
		width: 38,
		height: 38,
		borderRadius: 19,
		backgroundColor: '#F9FAFB',
		marginRight: 10,
	},
	postHeaderTextWrap: {
		flex: 1,
		paddingRight: 8,
	},
	postHeaderRight: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 8,
		marginLeft: 8,
	},
	postMetaGroup: {
		alignItems: 'flex-end',
	},
	postAuthorName: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: '900',
		color: '#31429B',
		flexShrink: 1,
	},
	postMetaRow: {
		flexDirection: 'row',
		alignItems: 'center',
		flexWrap: 'wrap',
		gap: 4,
		marginTop: 2,
	},
	postMeta: {
		fontSize: 11,
		fontWeight: '700',
		color: '#7A7A7A',
	},
	postMetaSeparator: {
		fontSize: 11,
		fontWeight: '800',
		color: '#7A7A7A',
	},
	postMenuButton: {
		width: 32,
		height: 32,
		alignItems: 'center',
		justifyContent: 'center',
	},
	postCaption: {
		fontSize: 15,
		lineHeight: 22,
		color: '#1F2937',
		marginBottom: 12,
	},
	captionBlock: {
		marginBottom: 12,
	},
	captionMeasureWrap: {
		position: 'absolute',
		opacity: 0,
		left: 0,
		right: 0,
		zIndex: -1,
	},
	captionMeasureText: {
		position: 'relative',
	},
	readMoreButton: {
		alignSelf: 'flex-start',
		marginTop: 4,
	},
	readMoreText: {
		fontSize: 13,
		fontWeight: '800',
		color: '#31429B',
	},
	captionMention: {
		fontWeight: '900',
		textDecorationLine: 'underline',
		color: '#F2C919',
	},
	announcementTitle: {
		fontSize: 16,
		lineHeight: 22,
		fontWeight: '800',
		color: '#111827',
		marginBottom: 4,
	},
	repostedOriginalCard: {
		borderRadius: 14,
		borderWidth: 1,
		borderColor: '#DFE4F2',
		backgroundColor: '#F9FAFE',
		paddingHorizontal: 10,
		paddingVertical: 10,
		marginBottom: 12,
	},
	repostedOriginalHeader: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	repostedOriginalAvatar: {
		width: 28,
		height: 28,
		borderRadius: 14,
		backgroundColor: '#E5E7EB',
		marginRight: 8,
	},
	repostedOriginalTextWrap: {
		flex: 1,
	},
	repostedOriginalAuthor: {
		fontSize: 12,
		fontWeight: '800',
		color: '#24346F',
	},
	repostedOriginalMeta: {
		fontSize: 10,
		fontWeight: '700',
		color: '#7A869A',
		marginTop: 1,
	},
	repostedOriginalCaption: {
		marginTop: 8,
		fontSize: 13,
		lineHeight: 18,
		color: '#334155',
	},
	repostedOriginalActionsRow: {
		flexDirection: 'row',
		justifyContent: 'flex-end',
		marginTop: 8,
	},
	postReactionRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'flex-start',
		flexWrap: 'nowrap',
		gap: 4,
		marginTop: 12,
		paddingTop: 0,
	},
	postCommentButton: {
		minWidth: 52,
		height: 32,
		paddingHorizontal: 10,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: 16,
		backgroundColor: '#F9FAFB',
		borderWidth: 1,
		borderColor: '#DDE3F0',
	},
	postActionButtonText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: '800',
		color: '#56607A',
	},
	postActionCount: {
		fontSize: 12,
		fontWeight: '800',
		color: '#5B647A',
		textAlign: 'center',
		marginLeft: 6,
	},
	postReactionButton: {
		minWidth: 52,
		height: 32,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 10,
		paddingVertical: 0,
		borderRadius: 16,
		backgroundColor: '#F9FAFB',
		borderWidth: 1,
		borderColor: '#DDE3F0',
	},
	postReactionButtonActive: {
		backgroundColor: '#EFF6FF',
		borderColor: '#C7D2FE',
	},
	postRepostButton: {
		minWidth: 52,
		height: 32,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 10,
		paddingVertical: 0,
		borderRadius: 16,
		backgroundColor: '#F9FAFB',
		borderWidth: 1,
		borderColor: '#DDE3F0',
	},
	postRepostButtonActive: {
		backgroundColor: '#ECFDF5',
		borderColor: '#BBF7D0',
	},
	postActionInline: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	postReactionButtonText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: '800',
		color: '#31429B',
	},
	postReactionButtonTextActive: {
		color: '#D92D20',
	},
	postRepostButtonTextActive: {
		color: '#15803D',
	},
	postTwoGrid: {
		flexDirection: 'row',
		gap: 8,
		alignItems: 'flex-start',
	},
	postTwoPrimaryTile: {
		flex: 1.15,
		borderRadius: 12,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postTwoSecondaryTile: {
		flex: 0.85,
		borderRadius: 12,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postThreeCollage: {
		flexDirection: 'row',
		gap: 8,
		alignItems: 'stretch',
	},
	postThreeLeftTile: {
		flex: 1.45,
		borderRadius: 5,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		aspectRatio: 0.92,
	},
	postThreeRightColumn: {
		flex: 0.9,
		gap: 8,
		alignSelf: 'stretch',
		justifyContent: 'space-between',
	},
	postThreeRightTile: {
		flex: 1,
		borderRadius: 5,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		width: '100%',
		aspectRatio: 1,
	},
	postFourGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		gap: 8,
	},
	postFourGridTile: {
		width: '48.5%',
		aspectRatio: 1,
		borderRadius: 5,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
	},
	postFourCollage: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 8,
		alignItems: 'flex-start',
	},
	postFourLeadTile: {
		flex: 1.45,
		borderRadius: 8,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postFourSideColumn: {
		flex: 0.9,
		gap: 8,
		alignSelf: 'flex-start',
	},
	postFourSideTile: {
		width: '100%',
		borderRadius: 8,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postFivePlusGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		gap: 8,
	},
	postFivePlusTile: {
		width: '48.5%',
		aspectRatio: 1,
		borderRadius: 8,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
	},
	postImageOverlay: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: 'rgba(20, 25, 42, 0.45)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	postImageOverlayText: {
		fontSize: 28,
		lineHeight: 32,
		fontWeight: '900',
		color: '#F9FAFB',
		textShadowColor: 'rgba(0, 0, 0, 0.35)',
		textShadowOffset: { width: 0, height: 1 },
		textShadowRadius: 4,
	},
	postSingleImageWrap: {
		borderRadius: 8,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		width: '100%',
		alignSelf: 'stretch',
	},
	postCollageImage: {
		width: '100%',
		height: '100%',
		backgroundColor: '#F3F4F6',
	},
	postImagePressable: {
		width: '100%',
		height: '100%',
	},
	viewerBackdrop: {
		flex: 1,
		backgroundColor: '#000000',
		alignItems: 'stretch',
		justifyContent: 'flex-start',
	},
	viewerContent: {
		flex: 1,
		backgroundColor: '#000000',
		position: 'relative',
	},
	viewerPager: {
		flex: 1,
	},
	viewerScrollContent: {
		flexGrow: 1,
	},
	viewerScrollItem: {
		width: SCREEN_WIDTH,
		height: SCREEN_HEIGHT,
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 0,
	},
	viewerImageCard: {
		width: '100%',
		height: '100%',
		borderRadius: 0,
		overflow: 'hidden',
		backgroundColor: '#000000',
		padding: 0,
		shadowColor: 'transparent',
		shadowOpacity: 0,
		shadowRadius: 0,
		shadowOffset: { width: 0, height: 0 },
		elevation: 0,
	},
	viewerSlide: {
		width: '100%',
		height: '100%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	viewerImagePressable: {
		width: '100%',
		height: '100%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	viewerImage: {
		backgroundColor: 'transparent',
		alignSelf: 'center',
	},
	viewerTopBar: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		paddingTop: 48,
		paddingHorizontal: 16,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	viewerTopButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'transparent',
	},
	viewerFooter: {
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		paddingHorizontal: 16,
		paddingTop: 18,
		paddingBottom: 20,
		backgroundColor: 'rgba(0, 0, 0, 0.70)',
	},
	viewerAuthorCard: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 14,
	},
	viewerAuthorPressable: {
		marginRight: 12,
	},
	viewerAuthorAvatar: {
		width: 52,
		height: 52,
		borderRadius: 26,
		backgroundColor: '#1F2937',
		borderWidth: 2,
		borderColor: '#2F80ED',
	},
	viewerAuthorTextWrap: {
		flex: 1,
	},
	viewerAuthorName: {
		fontSize: 20,
		lineHeight: 24,
		fontWeight: '500',
		color: '#F9FAFB',
	},
	viewerAuthorMetaRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		marginTop: 4,
	},
	viewerAuthorMeta: {
		fontSize: 12,
		fontWeight: '600',
		color: 'rgba(255, 255, 255, 0.82)',
	},
	viewerAuthorMetaSeparator: {
		fontSize: 11,
		fontWeight: '800',
		color: 'rgba(255, 255, 255, 0.70)',
	},
	viewerActionsRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-around',
		paddingTop: 8,
		paddingBottom: 10,
	},
	viewerActionButton: {
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
		minWidth: 72,
	},
	viewerActionLabel: {
		fontSize: 13,
		fontWeight: '600',
		color: '#F9FAFB',
	},
	viewerCountsRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		paddingTop: 2,
	},
	viewerCountText: {
		fontSize: 11,
		fontWeight: '700',
		color: 'rgba(255, 255, 255, 0.70)',
	},
	viewerDotsRow: {
		position: 'absolute',
		bottom: 34,
		alignSelf: 'center',
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	viewerDot: {
		width: 7,
		height: 7,
		borderRadius: 3.5,
		backgroundColor: 'rgba(255, 255, 255, 0.45)',
	},
	viewerDotActive: {
		width: 18,
		borderRadius: 5,
		backgroundColor: '#F9FAFB',
	},
	repostModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.58)',
		justifyContent: 'flex-end',
	},
	repostModalSafeArea: {
		flex: 1,
		justifyContent: 'flex-end',
	},
	repostModalCard: {
		width: '100%',
		height: '88%',
		borderTopLeftRadius: 24,
		borderTopRightRadius: 24,
		backgroundColor: '#F9FAFB',
		paddingHorizontal: 18,
		paddingTop: 16,
		paddingBottom: 24,
	},
	repostModalTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '900',
		color: '#24346F',
	},
	repostModalSubtitle: {
		marginTop: 4,
		fontSize: 12,
		fontWeight: '700',
		color: '#64748B',
		marginBottom: 12,
	},
	repostCaptionInput: {
		minHeight: 118,
		maxHeight: 220,
		borderRadius: 14,
		borderWidth: 1,
		borderColor: '#D9DDE8',
		backgroundColor: '#F8FAFC',
		paddingHorizontal: 12,
		paddingVertical: 10,
		fontSize: 14,
		lineHeight: 20,
		color: '#24346F',
	},
	mentionPanel: {
		marginHorizontal: 12,
		marginTop: 4,
		borderRadius: 14,
		backgroundColor: '#F9FAFB',
		borderWidth: 1,
		borderColor: '#D9E2FF',
		paddingVertical: 6,
		overflow: 'hidden',
	},
	commentMentionPanel: {
		marginHorizontal: 12,
		marginTop: 4,
		borderRadius: 14,
		backgroundColor: '#F9FAFB',
		borderWidth: 1,
		borderColor: '#D9E2FF',
		paddingVertical: 6,
		overflow: 'hidden',
	},
	mentionItem: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	mentionAvatar: {
		width: 28,
		height: 28,
		borderRadius: 14,
		marginRight: 8,
		backgroundColor: '#E5E7EB',
	},
	mentionName: {
		flex: 1,
		color: '#24346F',
		fontSize: 13,
		fontWeight: '700',
	},
	repostModalActionsRow: {
		marginTop: 14,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'flex-end',
		gap: 10,
	},
	repostCancelButton: {
		minWidth: 88,
		height: 40,
		borderRadius: 999,
		paddingHorizontal: 16,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#E2E8F0',
	},
	repostCancelButtonText: {
		fontSize: 13,
		fontWeight: '800',
		color: '#334155',
	},
	repostSubmitButton: {
		minWidth: 98,
		height: 40,
		borderRadius: 999,
		paddingHorizontal: 18,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#31429B',
	},
	repostSubmitButtonText: {
		fontSize: 13,
		fontWeight: '900',
		color: '#F9FAFB',
	},
	themedAlertBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.58)',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 24,
	},
	themedAlertCard: {
		width: '100%',
		maxWidth: 390,
		borderRadius: 18,
		paddingHorizontal: 18,
		paddingVertical: 16,
		backgroundColor: '#F9FAFB',
		borderWidth: 1,
		borderColor: '#DCE3F5',
	},
	themedAlertTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '900',
		color: '#24346F',
	},
	themedAlertMessage: {
		marginTop: 6,
		fontSize: 14,
		lineHeight: 20,
		fontWeight: '600',
		color: '#475569',
	},
	themedAlertActionsRow: {
		marginTop: 16,
		flexDirection: 'row',
		gap: 10,
		justifyContent: 'flex-end',
	},
	themedAlertButton: {
		minWidth: 88,
		height: 38,
		paddingHorizontal: 14,
		borderRadius: 999,
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
	},
	themedAlertButtonNeutral: {
		backgroundColor: '#E2E8F0',
	},
	themedAlertButtonDestructive: {
		backgroundColor: '#FEE2E2',
	},
	themedAlertButtonText: {
		fontSize: 13,
		fontWeight: '900',
		color: '#F9FAFB',
	},
	themedAlertButtonTextNeutral: {
		color: '#334155',
	},
	themedAlertButtonTextDestructive: {
		color: '#B42318',
	},
	commentsModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.58)',
		justifyContent: 'flex-end',
	},
	postActionsBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.58)',
		alignItems: 'stretch',
		justifyContent: 'flex-end',
		paddingHorizontal: 0,
	},
	postActionsSafeArea: {
		flex: 1,
		justifyContent: 'flex-end',
		alignItems: 'stretch',
	},
	deleteLoadingBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.58)',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 18,
	},
	deleteLoadingCard: {
		width: '100%',
		maxWidth: 320,
		backgroundColor: '#F9FAFB',
		borderRadius: 22,
		paddingVertical: 24,
		paddingHorizontal: 20,
		alignItems: 'center',
		borderWidth: 1,
		borderColor: '#DCE3F5',
	},
	deleteLoadingTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '900',
		color: '#24346F',
		marginTop: 14,
	},
	deleteLoadingText: {
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '600',
		color: '#475569',
		textAlign: 'center',
		marginTop: 6,
	},
	postActionsCard: {
		width: '100%',
		backgroundColor: '#F9FAFB',
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		paddingTop: 12,
		paddingBottom: 18,
		paddingHorizontal: 12,
		borderWidth: 0,
	},
	postActionsHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 8,
	},
	postActionsTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '900',
		color: '#24346F',
	},
	postActionsCloseButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#EEF2FF',
	},
	postActionsSubtitle: {
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '600',
		color: '#475569',
		marginBottom: 14,
	},
	postActionsRow: {
		flexDirection: 'row',
		gap: 10,
		marginBottom: 12,
	},
	postActionChoiceButton: {
		flex: 1,
		minHeight: 44,
		borderRadius: 999,
		paddingHorizontal: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
		backgroundColor: '#EEF2FF',
	},
	postActionChoiceText: {
		fontSize: 13,
		fontWeight: '800',
		color: '#31429B',
	},
	postActionsLabel: {
		fontSize: 12,
		fontWeight: '800',
		color: '#475569',
		marginBottom: 8,
	},
	postVisibilityChoicesRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 8,
		marginBottom: 14,
	},
	postVisibilityChoice: {
		borderWidth: 1,
		borderColor: '#D9E2FF',
		backgroundColor: '#F8FAFF',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 8,
	},
	postVisibilityChoiceSelected: {
		borderColor: '#AFC0F7',
		backgroundColor: '#EAF0FF',
	},
	postVisibilityChoiceText: {
		color: '#31429B',
		fontSize: 12,
		fontWeight: '800',
	},
	postDeleteButton: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
		borderRadius: 999,
		borderWidth: 1,
		borderColor: '#FECACA',
		backgroundColor: '#FEF2F2',
		paddingVertical: 10,
	},
	postDeleteButtonText: {
		color: '#B42318',
		fontSize: 13,
		fontWeight: '800',
	},
	commentsSheet: {
		backgroundColor: '#F9FAFB',
		borderTopLeftRadius: 28,
		borderTopRightRadius: 28,
		paddingHorizontal: 16,
		paddingTop: 12,
		paddingBottom: 24,
		height: '94%',
	},
	commentsHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		minHeight: 52,
		marginBottom: 12,
		position: 'relative',
	},
	commentsHeaderCenter: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 4,
		alignSelf: 'center',
	},
	commentsTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontFamily: 'Poppins_700Bold',
		color: '#31429B',
	},
	commentsHeaderFilter: {
		width: 22,
		height: 22,
		borderRadius: 11,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'transparent',
	},
	commentsCloseButton: {
		position: 'absolute',
		right: 0,
		top: 10,
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'transparent',
	},
	commentsEmptyState: {
		flexGrow: 1,
		minHeight: 150,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: '#E5E7EB',
		backgroundColor: '#FAFBFD',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 10,
		paddingHorizontal: 18,
		marginBottom: 16,
	},
	commentsEmptyText: {
		fontSize: 12,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
		textAlign: 'center',
	},
	commentsBody: {
		flex: 1,
		minHeight: 0,
		marginBottom: 16,
	},
	commentsList: {
		flex: 1,
		minHeight: 0,
	},
	commentsListContent: {
		paddingBottom: 8,
	},
	commentItem: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 10,
		marginBottom: 12,
	},
	commentAvatar: {
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: '#E5E7EB',
	},
	commentAuthorName: {
		fontSize: 14,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
		marginBottom: 2,
	},
	commentTimestamp: {
		fontSize: 11,
		fontFamily: 'Poppins_400Regular',
		color: '#6B7280',
	},
	commentText: {
		fontSize: 14,
		lineHeight: 20,
		fontFamily: 'Poppins_400Regular',
		color: '#1F2937',
	},
	commentContentColumn: {
		flex: 1,
		alignSelf: 'stretch',
		minWidth: 0,
	},
	commentThread: {
		marginBottom: 14,
	},
	commentMetaRow: {
		marginTop: 6,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
	},
	commentReplyButton: {
		paddingHorizontal: 0,
		paddingVertical: 0,
	},
	commentReplyButtonText: {
		fontSize: 12,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
	},
	commentItemReply: {
		marginLeft: 30,
	},
	viewRepliesRow: {
		marginTop: 0,
		marginLeft: 16,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		paddingVertical: 6,
	},
	viewRepliesLine: {
		width: 28,
		height: 1,
		backgroundColor: '#E2E8F0',
	},
	viewRepliesText: {
		fontSize: 13,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
	},
	commentRepliesList: {
		marginTop: 0,
		paddingLeft: 16,
	},
	commentNestedRepliesList: {
		marginTop: 0,
		paddingLeft: 0,
	},
	hideRepliesRow: {
		marginTop: 6,
		marginLeft: 16,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		paddingVertical: 4,
	},
	hideRepliesText: {
		fontSize: 12,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
	},
	commentReplyWrap: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 8,
		marginTop: 8,
	},
	commentReplyWrapLast: {
		marginBottom: 0,
	},
	commentReplyLineColumn: {
		width: 16,
		alignItems: 'center',
		justifyContent: 'flex-start',
		paddingTop: 2,
	},
	commentReplyLine: {
		width: 1,
		flex: 1,
		minHeight: 22,
		backgroundColor: '#E2E8F0',
	},
	commentReplyContent: {
		flex: 1,
		minWidth: 0,
	},
	commentReplyHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 4,
		marginBottom: 2,
	},
	commentReplyingToHandle: {
		fontSize: 11,
		fontFamily: 'Poppins_400Regular',
		color: '#9AA3B2',
	},
	commentReplyAuthorName: {
		fontSize: 13,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
	},
	commentReplyText: {
		fontSize: 14,
		lineHeight: 20,
		fontFamily: 'Poppins_400Regular',
		color: '#1F2937',
	},
	commentReplyMetaRow: {
		marginTop: 6,
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
	},
	commentActionColumn: {
		alignItems: 'center',
		justifyContent: 'center',
		minWidth: 42,
		paddingTop: 0,
	},
	commentActionButton: {
		padding: 4,
		marginBottom: 2,
	},
	commentLikeCount: {
		marginTop: 1,
		fontSize: 11,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
	},
	commentComposer: {
		flexDirection: 'row',
		alignItems: 'flex-end',
		gap: 0,
		paddingTop: 2,
	},
	commentComposerSafeArea: {
		marginTop: 1,
	},
	commentComposerContent: {
		flex: 1,
	},
	commentReplyContext: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 8,
		marginBottom: 8,
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 14,
		backgroundColor: '#EEF2FF',
	},
	commentReplyContextText: {
		flex: 1,
		fontSize: 12,
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
	},
	commentReplyContextCancel: {
		width: 28,
		height: 28,
		borderRadius: 14,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F9FAFB',
	},
	commentInputWrap: {
		minHeight: 46,
		maxHeight: 84,
		marginTop: 10,
		borderWidth: 1,
		borderColor: '#D7DDF1',
		borderRadius: 14,
		backgroundColor: '#F8FAFC',
		shadowColor: '#111827',
		shadowOpacity: 0.12,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 4 },
		elevation: 3,
	},
	commentInput: {
		minHeight: 46,
		paddingHorizontal: 14,
		paddingRight: 56,
		paddingTop: 12,
		paddingBottom: 6,
		borderWidth: 0,
		backgroundColor: 'transparent',
		fontSize: 14,
		lineHeight: 20,
		fontFamily: 'Poppins_400Regular',
		color: '#31429B',
	},
	commentSendButtonInside: {
		position: 'absolute',
		top: 5,
		right: 8,
		minWidth: 36,
		height: 36,
		borderRadius: 18,
		paddingHorizontal: 10,
		zIndex: 2,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#31429B',
	},
	commentSendButtonDisabled: {
		opacity: 0.45,
	},
	commentSendButtonText: {
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '800',
		color: '#F9FAFB',
	},
	postSingleImage: {
		width: '100%',
		height: '100%',
		backgroundColor: '#F3F4F6',
	},
	postMediaImage: {
		width: '100%',
		height: '100%',
		backgroundColor: '#F3F4F6',
	},
	emptySpace: {
		flex: 1,
		minHeight: 220,
	},
});

export default styles;
