import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    paddingTop: Platform.OS === 'ios' ? 120 : 100,
    flexGrow: 1,
    backgroundColor: "#FFFFFF",
  },

  // --- WHITE HERO SECTION ---
  heroSection: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 24,
  },
  heroRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatar: {
    backgroundColor: "#E2E8F0",
    marginRight: 20,
    borderWidth: 2,
    borderColor: "#F1F5F9",
  },
  heroCopy: {
    flex: 1,
  },
  name: {
    fontSize: 22,
    color: "#1C1C1E",
    fontFamily: "Poppins_700Bold",
    lineHeight: 30,
    marginBottom: 8,
  },
  tagPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#FFD404",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginBottom: 10,
  },
  tagText: {
    marginLeft: 6,
    fontSize: 10,
    color: "#31429B",
    fontFamily: "Poppins_600SemiBold",
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 12,
  },
  statText: {
    fontSize: 12,
    color: "#64748B",
    fontFamily: "Poppins_400Regular",
  },
  statNumber: {
    fontSize: 14,
    color: "#1C1C1E",
    fontFamily: "Poppins_700Bold",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  editProfileButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#94A3B8",
    backgroundColor: "#FFFFFF",
    gap: 6,
  },
  editProfileText: {
    fontSize: 13,
    color: "#1C1C1E",
    fontFamily: "Poppins_600SemiBold",
  },
  settingsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#31429B",
    alignItems: "center",
    justifyContent: "center",
  },

  // --- ABOUT ME ---
  aboutSection: {
    marginTop: 20,
  },
  sectionHeadingBlack: {
    fontSize: 20,
    color: "#1C1C1E",
    fontFamily: "Poppins_700Bold",
    marginBottom: 12,
  },
  aboutItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  aboutIcon: {
    width: 24,
    textAlign: "center",
  },
  aboutText: {
    fontSize: 15,
    color: "#333333",
    fontFamily: "Poppins_500Medium",
    marginLeft: 8,
    flex: 1,
  },

  // --- DARK SECTION ---
  darkSection: {
    backgroundColor: "#1F2B67",
    paddingLeft: 20, 
    paddingTop: 32,
    paddingBottom: 40,
    overflow: "hidden", 
  },
  sectionHeadingYellow: {
    fontSize: 20,
    color: "#FFD404",
    fontFamily: "Poppins_700Bold",
    marginBottom: 12,
  },
  biographyText: {
    fontSize: 14,
    lineHeight: 24,
    color: "#FFFFFF",
    fontFamily: "Poppins_400Regular",
    marginBottom: 32,
  },
  darkSectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  outlineEditPill: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 4,
    gap: 4,
  },
  outlineEditText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontFamily: "Poppins_500Medium",
  },

  // --- WORK EXPERIENCE CARDS ---
  workScrollContent: {
    gap: 16,
    paddingBottom: 32,
  },
  workCard: {
    width: 240,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    alignItems: "center",
    marginRight: 16,
  },
  workMenuIcon: {
    position: "absolute",
    top: 16,
    right: 16,
  },
  workBriefcase: {
    marginBottom: 12,
  },
  workTitle: {
    fontSize: 18,
    color: "#1C1C1E",
    fontFamily: "Poppins_700Bold",
    textAlign: "center",
  },
  workSubtitle: {
    fontSize: 12,
    color: "#1C1C1E",
    fontFamily: "Poppins_500Medium",
    textAlign: "center",
    marginTop: 4,
    marginBottom: 8,
  },
  workPeriod: {
    fontSize: 12,
    color: "#1C1C1E",
    fontFamily: "Poppins_700Bold",
    textAlign: "center",
    marginBottom: 12,
  },
  workDescription: {
    fontSize: 12,
    color: "#64748B",
    fontFamily: "Poppins_400Regular",
    textAlign: "center",
    lineHeight: 18,
  },

  // --- SKILLS GRID ---
  skillsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 24,
  },
  skillPill: {
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  skillText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
  },
  viewAllButton: {
    alignSelf: "center",
    backgroundColor: "#FFD404",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  viewAllText: {
    color: "#1F2B67",
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
  },

  // --- POSTS SECTION ---
  postsSection: {
    backgroundColor: "#F5F6FA",
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 40,
  },
  postsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  createPostPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#94A3B8",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 6,
  },
  createPostPillText: {
    fontSize: 12,
    color: "#1C1C1E",
    fontFamily: "Poppins_600SemiBold",
  },

  // --- POST STYLING (PORTED FROM FEED) ---
  repostWrapper: {
    backgroundColor: "#FFD404",
    borderRadius: 20,
    marginBottom: 16,
    paddingTop: 14,
  },
  repostBanner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  repostBannerAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: "#E5E7EB",
  },
  repostBannerText: {
    fontSize: 14,
    color: "#1F2937",
    fontFamily: "Poppins_400Regular",
  },
  repostBannerName: {
    fontFamily: "Poppins_700Bold",
  },
  repostInnerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
  },
  postCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  postHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  postAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#E5E7EB",
    marginRight: 12,
  },
  postHeaderTextWrap: {
    flex: 1,
    paddingRight: 8,
    justifyContent: "center",
  },
  postAuthorName: {
    fontSize: 16,
    color: "#1C1C1E",
    fontFamily: "Poppins_700Bold",
    marginBottom: 2,
  },
  postMeta: {
    fontSize: 12,
    color: "#6B7280",
    fontFamily: "Poppins_400Regular",
  },
  postMenuButton: {
    width: 28,
    height: 28,
    alignItems: "flex-end",
  },
  postCaption: {
    fontSize: 15,
    lineHeight: 22,
    color: "#1C1C1E",
    fontFamily: "Poppins_400Regular",
    marginBottom: 12,
  },
  postSingleImageWrap: {
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#F3F4F6",
    width: "100%",
  },
  postTwoGrid: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  postTwoPrimaryTile: { flex: 1.15, borderRadius: 12, overflow: "hidden", backgroundColor: "#F3F4F6" },
  postTwoSecondaryTile: { flex: 0.85, borderRadius: 12, overflow: "hidden", backgroundColor: "#F3F4F6" },
  postThreeCollage: { flexDirection: "row", gap: 8, alignItems: "stretch" },
  postThreeLeftTile: { flex: 1.45, borderRadius: 12, overflow: "hidden", backgroundColor: "#F3F4F6", aspectRatio: 0.92 },
  postThreeRightColumn: { flex: 0.9, gap: 8, alignSelf: "stretch", justifyContent: "space-between" },
  postThreeRightTile: { flex: 1, borderRadius: 12, overflow: "hidden", backgroundColor: "#F3F4F6", aspectRatio: 1 },
  postFourGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 8 },
  postFourGridTile: { width: "48.5%", aspectRatio: 1, borderRadius: 12, overflow: "hidden", backgroundColor: "#F3F4F6" },
  postFivePlusGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 8 },
  postFivePlusTile: { width: "48.5%", aspectRatio: 1, borderRadius: 12, overflow: "hidden", backgroundColor: "#F3F4F6" },
  postCollageImage: { width: "100%", height: "100%", backgroundColor: "#F3F4F6" },
  postImageOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(20, 25, 42, 0.45)", alignItems: "center", justifyContent: "center" },
  postImageOverlayText: { fontSize: 28, color: "#F9FAFB", fontFamily: "Poppins_700Bold" },
  postReactionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    gap: 16, 
  },
  postActionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  postActionCount: {
    fontSize: 14,
    color: "#31429B",
    fontFamily: "Poppins_500Medium",
  },
  emptyPostsText: {
    fontSize: 14,
    color: "#64748B",
    fontFamily: "Poppins_400Regular",
    textAlign: "center",
    marginTop: 20,
  },

  // --- MODALS ---
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    color: "#1C1C1E",
    fontFamily: "Poppins_700Bold",
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  modalHelperText: {
    fontSize: 14,
    color: "#64748B",
    fontFamily: "Poppins_400Regular",
    marginBottom: 20,
  },
  bioInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 16,
    padding: 16,
    fontSize: 14,
    color: "#1C1C1E",
    fontFamily: "Poppins_400Regular",
    minHeight: 120,
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 24,
  },
  modalActionButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    minWidth: 100,
    alignItems: "center",
  },
  modalCancelButton: {
    backgroundColor: "#F1F5F9",
  },
  modalCancelButtonText: {
    color: "#475569",
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
  },
  modalSaveButton: {
    backgroundColor: "#31429B",
  },
  modalSaveButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
  },
});

export default styles;