import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#31429B',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  brandHeader: {
    backgroundColor: '#31429B',
  },
  brandRow: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandLogo: {
    width: 136,
    height: 42,
  },
  nulipaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    minWidth: 122,
    justifyContent: 'center',
  },
  nulipaIcon: {
    width: 22,
    height: 22,
    marginRight: 6,
  },
  nulipaText: {
    color: '#31429B',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  brandAccent: {
    height: 10,
    backgroundColor: '#F3CB21',
  },
  content: {
    flexGrow: 1,
    paddingBottom: 18,
    backgroundColor: '#FFFFFF',
  },
  stateWrap: {
    minHeight: 420,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 20,
  },
  errorText: {
    color: '#B91C1C',
    textAlign: 'center',
    fontSize: 15,
  },
  actionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: '#31429B',
    borderRadius: 14,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  heroCard: {
    marginTop: 0,
    marginHorizontal: 0,
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 38,
    borderBottomRightRadius: 38,
    padding: 16,
    marginBottom: -24,
    position: 'relative',
    zIndex: 2,
    shadowColor: '#111827',
    shadowOpacity: 0.10,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    backgroundColor: '#E5E7EB',
    marginRight: 14,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  name: {
    flex: 1,
    paddingRight: 8,
    color: '#384A9C',
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '900',
  },
  iconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#384A9C',
  },
  tagPill: {
    marginTop: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#FFD84D',
  },
  tagText: {
    marginLeft: 4,
    color: '#31429B',
    fontSize: 11,
    fontWeight: '800',
  },
  statsRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  statBlock: {
    minWidth: 64,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  statValue: {
    fontSize: 24,
    lineHeight: 26,
    color: '#30343C',
    fontWeight: '500',
  },
  statLabel: {
    marginTop: 2,
    color: '#5C6471',
    fontSize: 12,
    textAlign: 'center',
  },
  sectionBlock: {
    marginTop: 18,
    paddingHorizontal: 0,
  },
  postsSectionBlock: {
    marginTop: 18,
    paddingHorizontal: 10,
  },
  postsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  createPostButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#31429B',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  createPostButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  aboutSectionWrap: {
    marginTop: 1,
    paddingHorizontal: 0,
    position: 'relative',
    zIndex: 1,
  },
  aboutSectionCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 32,
    paddingBottom: 12,
    minHeight: 150,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  bioSectionCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 12,
    minHeight: 150,
    borderRadius: 22,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workSectionCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 12,
    borderRadius: 22,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workPagerContent: {
    alignItems: 'stretch',
    marginBottom: 12,
  },
  workPage: {
    paddingRight: 12,
  },
  sectionHeading: {
    color: '#404040',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  editPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#B8BCC6',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#FFFFFF',
  },
  editPillText: {
    color: '#404040',
    fontSize: 11,
    fontWeight: '700',
  },
  workDeletePill: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#f59f9f',
  },
  workDeletePillText: {
    color: '#B91C1C',
    fontSize: 11,
    fontWeight: '700',
  },
  aboutItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    marginBottom: 6,
  },
  aboutText: {
    marginLeft: 8,
    color: '#404040',
    fontSize: 14,
  },
  biographyText: {
    color: '#404040',
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  modalCard: {
    width: '85%',
    maxWidth: 550,
    maxHeight: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    shadowColor: '#111827',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modalTitle: {
    color: '#31429B',
    fontSize: 18,
    fontWeight: '900',
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF',
  },
  modalHelperText: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  input: {
    borderBottomWidth: 2,
    borderBottomColor: '#31429B',
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 10,
    color: '#1F2937',
    fontSize: 14,
    lineHeight: 20,
  },
  bioInput: {
    borderBottomWidth: 2,
    borderBottomColor: '#31429B',
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 10,
    color: '#1F2937',
    fontSize: 14,
    lineHeight: 20,
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 16,
  },
  modalActionButton: {
    minWidth: 96,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelButton: {
    backgroundColor: '#E2E8F0',
  },
  modalCancelButtonText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '800',
  },
  modalSaveButton: {
    backgroundColor: '#31429B',
  },
  modalSaveButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  workCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 10,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  workRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  workNavButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#111827',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workContent: {
    flex: 1,
    paddingHorizontal: 10,
  },
  workTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  workTitle: {
    marginLeft: 6,
    color: '#30343C',
    fontSize: 15,
    fontWeight: '800',
  },
  workSubtitle: {
    marginTop: 2,
    color: '#31429B',
    fontSize: 12,
    fontWeight: '600',
  },
  workPeriod: {
    marginTop: 10,
    color: '#5C6471',
    fontSize: 12,
  },
  workLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  workLocation: {
    marginLeft: 6,
    color: '#5C6471',
    fontSize: 12,
  },
  workDescription: {
    marginTop: 10,
    color: '#404040',
    fontSize: 12,
    lineHeight: 18,
  },
  paginationRow: {
    marginTop: 10,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  paginationDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    marginHorizontal: 3,
    backgroundColor: '#D9DCE3',
  },
  paginationDotActive: {
    width: 18,
    backgroundColor: '#31429B',
  },
  postsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    minHeight: 84,
  },
  profilePostItem: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  profilePostHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 8,
  },
  profilePostHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  profilePostStatusGroup: {
    alignItems: 'flex-end',
  },
  profilePostTypePill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    gap: 4,
  },
  profilePostPill: {
    backgroundColor: '#EEF2FF',
  },
  profileRepostPill: {
    backgroundColor: '#DCFCE7',
  },
  profilePostTypeText: {
    color: '#31429B',
    fontSize: 11,
    fontWeight: '800',
  },
  profileRepostTypeText: {
    color: '#15803D',
  },
  profilePostTime: {
    color: '#7A869A',
    fontSize: 10,
    fontWeight: '700',
  },
  profilePostVisibilityText: {
    marginTop: 2,
    color: '#31429B',
    fontSize: 10,
    fontWeight: '800',
  },
  profilePostMenuButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF',
  },
  profilePostCaption: {
    color: '#334155',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  profileOriginalWrap: {
    borderWidth: 1,
    borderColor: '#DCE3F5',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  profileOriginalLabel: {
    color: '#475569',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 4,
  },
  profileOriginalCaption: {
    color: '#334155',
    fontSize: 12,
    lineHeight: 17,
  },
  profilePostImagesGrid: {
    marginBottom: 8,
    gap: 8,
  },
  profilePostImagesRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  profilePostImageTile: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#E2E8F0',
  },
  profilePostImageTileWithGap: {
    marginRight: 8,
  },
  profilePostImageTileSpacer: {
    flex: 1,
  },
  profilePostImageTileSingle: {
    flex: 0,
    width: '100%',
    aspectRatio: 1.2,
  },
  profilePostImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E2E8F0',
  },
  profilePostImageOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  profilePostImageOverlayText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  profilePostMetricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profilePostMetricText: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '700',
  },
  emptyPostsText: {
    color: '#8A8F9A',
    fontSize: 13,
  },
  postActionOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  postActionCard: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    shadowColor: '#111827',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  postActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  postActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#EEF2FF',
    borderRadius: 999,
    paddingVertical: 10,
  },
  postActionButtonText: {
    color: '#31429B',
    fontSize: 13,
    fontWeight: '800',
  },
  postActionSectionLabel: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
  },
  postVisibilityRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  postVisibilityPill: {
    borderWidth: 1,
    borderColor: '#D9E2FF',
    backgroundColor: '#F8FAFF',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  postVisibilityPillSelected: {
    borderColor: '#AFC0F7',
    backgroundColor: '#EAF0FF',
  },
  postVisibilityPillText: {
    color: '#31429B',
    fontSize: 12,
    fontWeight: '800',
  },
  postDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    paddingVertical: 10,
  },
  postDeleteButtonText: {
    color: '#B91C1C',
    fontSize: 13,
    fontWeight: '800',
  },
});

export default styles;