import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F7F9FC',
	},
	scrollContent: {
		paddingBottom: 24,
	},
	headerCard: {
		paddingHorizontal: 10,
		paddingTop: 12,
		paddingBottom: 14,
		backgroundColor: '#FFFFFF',
	},
	backButton: {
		flexDirection: 'row',
		alignItems: 'center',
		alignSelf: 'flex-start',
		gap: 6,
		marginBottom: 12,
		paddingVertical: 6,
		paddingHorizontal: 2,
	},
	backButtonText: {
		fontSize: 13,
		fontWeight: '800',
		color: '#31429B',
		fontFamily: 'Poppins_700Bold',
	},
	heroImage: {
		height: 200,
		borderRadius: 18,
		overflow: 'hidden',
		backgroundColor: '#E5E7EB',
	},
	heroImageInner: {
		borderRadius: 18,
	},
	heroOverlay: {
		flex: 1,
		backgroundColor: 'rgba(49, 66, 155, 0.15)',
	},
	heroPlaceholder: {
		height: 200,
		borderRadius: 18,
		backgroundColor: '#E8EEFF',
		alignItems: 'center',
		justifyContent: 'center',
	},
	contentCard: {
		marginHorizontal: 10,
		marginTop: 14,
		backgroundColor: '#FFFFFF',
		borderRadius: 20,
		paddingHorizontal: 16,
		paddingVertical: 18,
		shadowColor: '#000',
		shadowOpacity: 0.06,
		shadowRadius: 12,
		shadowOffset: { width: 0, height: 6 },
		elevation: 4,
	},
	title: {
		fontSize: 22,
		lineHeight: 28,
		fontWeight: '900',
		fontFamily: 'Poppins_700Bold',
		color: '#31429B',
	},
	description: {
		marginTop: 10,
		fontSize: 15,
		lineHeight: 23,
		fontFamily: 'Poppins_400Regular',
		color: '#334155',
	},
	gallerySection: {
		marginTop: 14,
	},
	galleryLabel: {
		fontSize: 12,
		fontWeight: '800',
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	descriptionLabelSpacing: {
		marginTop: 8,
	},
	galleryScroll: {
		paddingTop: 10,
		gap: 10,
	},
	galleryGrid: {
		marginTop: 10,
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		rowGap: 10,
	},
	galleryGridItem: {
		width: '48.5%',
		height: 120,
		borderRadius: 16,
		overflow: 'hidden',
		backgroundColor: '#E5E7EB',
		marginBottom: 10,
	},
	galleryGridImage: {
		width: '100%',
		height: '100%',
	},
	galleryImageWrap: {
		width: 96,
		height: 96,
		borderRadius: 16,
		overflow: 'hidden',
		backgroundColor: '#E5E7EB',
		marginRight: 10,
	},
	galleryImage: {
		width: '100%',
		height: '100%',
	},
	galleryModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.88)',
		alignItems: 'center',
		justifyContent: 'center',
		padding: 0,
	},
	galleryModalContent: {
		width: '100%',
		height: '100%',
		backgroundColor: '#0F172A',
		overflow: 'hidden',
	},
	galleryModalStage: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	galleryModalScroll: {
		flex: 1,
	},
	galleryModalScrollContent: {
		flexGrow: 1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	galleryModalCloseButton: {
		position: 'absolute',
		top: 14,
		right: 14,
		zIndex: 2,
		width: 36,
		height: 36,
		borderRadius: 18,
		backgroundColor: 'rgba(255, 255, 255, 0.92)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	galleryModalImage: {
		flex: 1,
		width: '100%',
		height: '100%',
		backgroundColor: '#0F172A',
	},
	infoRow: {
		marginTop: 18,
		gap: 12,
	},
	infoItem: {
		padding: 14,
		borderRadius: 16,
		backgroundColor: '#F8FAFF',
		borderWidth: 1,
		borderColor: '#E2E8F0',
	},
	infoLabel: {
		fontSize: 12,
		fontWeight: '800',
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	infoValue: {
		marginTop: 6,
		fontSize: 15,
		lineHeight: 21,
		fontWeight: '700',
		fontFamily: 'Poppins_600SemiBold',
		color: '#1F2937',
	},
	platformLink: {
		color: '#31429B',
		textDecorationLine: 'underline',
	},
	venueCard: {
		marginTop: 18,
		padding: 14,
		borderRadius: 18,
		backgroundColor: '#F8FAFF',
		borderWidth: 1,
		borderColor: '#D9E2FF',
	},
	venueHeaderRow: {
		flexDirection: 'column',
		alignItems: 'flex-start',
		gap: 4,
	},
	venueTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	venueLabel: {
		fontSize: 12,
		fontWeight: '800',
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
		textTransform: 'uppercase',
		letterSpacing: 0.4,
	},
	venueName: {
		marginTop: 6,
		fontSize: 16,
		lineHeight: 22,
		fontWeight: '900',
		fontFamily: 'Poppins_700Bold',
		color: '#31429B',
	},
	venueAddress: {
		marginTop: 8,
		fontSize: 14,
		lineHeight: 21,
		fontFamily: 'Poppins_400Regular',
		color: '#334155',
	},
	mapContainer: {
		marginTop: 14,
		height: 220,
		borderRadius: 16,
		overflow: 'hidden',
		backgroundColor: '#E5E7EB',
	},
	mapImage: {
		width: '100%',
		height: '100%',
	},
	mapWebView: {
		width: '100%',
		height: '100%',
		backgroundColor: '#E5E7EB',
	},
	mapOverlay: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: 'rgba(15, 23, 42, 0.08)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	mapPinWrap: {
		width: 44,
		height: 44,
		borderRadius: 22,
		backgroundColor: 'rgba(255, 255, 255, 0.88)',
		alignItems: 'center',
		justifyContent: 'center',
		shadowColor: '#000',
		shadowOpacity: 0.12,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
		elevation: 3,
	},
	coordinateText: {
		marginTop: 10,
		fontSize: 12,
		lineHeight: 18,
		fontWeight: '700',
		fontFamily: 'Poppins_600SemiBold',
		color: '#31429B',
	},
	mapFallback: {
		marginTop: 14,
		minHeight: 220,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: '#CBD5E1',
		backgroundColor: '#EEF2FF',
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 16,
	},
	mapFallbackText: {
		marginTop: 8,
		fontSize: 13,
		lineHeight: 19,
		fontFamily: 'Poppins_400Regular',
		color: '#31429B',
		textAlign: 'center',
	},
	registerButtonContainer: {
		marginTop: 18,
		paddingTop: 14,
		borderTopWidth: 1,
		borderTopColor: '#D9E2FF',
	},
	registerButton: {
		height: 46,
		borderRadius: 999,
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 1,
		borderColor: '#31429B',
	},
	registerButtonDestructive: {
		backgroundColor: '#D92D20',
		borderColor: '#D92D20',
	},
	registerButtonDisabled: {
		opacity: 0.45,
	},
	registerButtonText: {
		fontSize: 15,
		lineHeight: 20,
		fontWeight: '800',
		fontFamily: 'Poppins_700Bold',
		color: '#FFFFFF',
	},
});

export default styles;